### ISSUE TITLE
Create radio component

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2023-bsa-talents#10]
It should be radio and radio group component

![Image](https://user-images.githubusercontent.com/105710998/261637316-95b00501-dd15-4ffa-854f-8459153fdabd.png)

https://mui.com/material-ui/react-radio-button/#radio-group

**Comment by anton-otroshchenko** [comment]
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/105710998/43403727-c14c-40e5-b6ac-944992ec3701)

**Comment by savinaDaria** [comment]
There are properties in the Radio element like **checkedIcon and icon** that allow making the circle styling as shown in the screenshot. Should I implement an Icon component so that I can pass it there? Or will everything be handled through the **sx** property?
