### ISSUE TITLE
Create BSA badges screen

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#108]
Create BSA Badges screen, just UI for now

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/103518438/661789a8-600d-4866-a5f4-7299f4c21504)

**Comment by anna9314** [comment]
[BUG] Badges aren't displayed as selected by default #331

**Comment by mskmee** [comment]
It's will work after this pr confirmed: https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/pull/223

**Comment by Oleksandrra** [comment]
[BUG]: Button “Back” doesn’t redirect to the previous page on the page “Step 02/05”
https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/343
