### ISSUE TITLE
Create Onboarding Step 3 screen and logic

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#109]
Create Skills & Project screen 

User story:

As a talent, I want to be able to fill up a profile with skills and projects information, so that potential employers are able to find out about my skills before contact me.

Acceptance criteria:

- The registration step “STEP 03/05” is placed in the upper right corner on the same line with the title “CV and contacts”
- “Hard skills”, “Level of English”, “Preferred language of communication”, “I do not consider” fields must be mandatory and have “*”
- “Hard skills”, “Level of English”, “Preferred language of communication”, “Project links” fields must contain placeholder
- Skills and projects page must include input fields for “Hard skills”, “Project links”
- “Level of English” should be dropdown
- “Preferred language of communication” should be a dropdown with ticks to choose  more than one language
- “I do not consider” checkbox should have 5 options: Gambling, Dating, Gamedev, Crypto, Startups, talent should be able to choose several options
- When talent enters hard skill it should appear search suggestion, after choosing hard skill should appear under the “Hard skills” field
- “Level of English” dropdown should have options: No English, A1 Elementary, A2 Pre-intermediate, B1 Intermediate, B2 Upper intermediate, C1 Advanced, C2 Proficiency
- “Preferred language of communication” dropdown should have options: English, Ukrainian, Russian, Spanish, Portuguese, French, German, and Chinese (Mandarin)
- Talent should be able to add Project link, if the talent typed an invalid URL, should see a validation message
- Talent should be able to add other project links, by clicking on “+Add more link”
- Talent should be able to add up to 5 project links
- Talent should be able to delete added links by clicking on the delete icon

![Image](https://user-images.githubusercontent.com/103518438/263259330-2e41b548-1766-4401-925f-4210813634ff.png)

**Comment by anna9314** [comment]
[BUG] The layout of the Step 03 page does not match the approved design #387

**Comment by anna9314** [comment]
[BUG] The next button doesn't work on the Step 03 #388
