### ISSUE TITLE
Create checkbox component

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2023-bsa-talents#11]
![Image](https://user-images.githubusercontent.com/105710998/261637137-f10b7a7d-2e8b-4ed5-93fa-58115e0d08c4.png)

https://mui.com/material-ui/react-checkbox/

**Comment by anton-otroshchenko** [comment]
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/105710998/e43fc2df-c40f-435d-9e10-6cc269cbc04d)

**Comment by ptarho** [comment]
Should our custom checkbox be controlled with a useState?
