### ISSUE TITLE
Create shared Photo picker component for CV screen

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#111]
Create a photo picker component for future CV screen. Text and button should be under the [Avatar component](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/110). 

Let's use this lib [https://github.com/react-native-image-picker/react-native-image-picker](https://github.com/react-native-image-picker/react-native-image-picker)

There should be 2 options: launch gallery or take picture from camera. 

![Image](https://user-images.githubusercontent.com/103518438/263260344-02fee7ae-9de0-42cf-bf27-c2f5ffc8745f.png)

**Comment by anna9314** [comment]
Blocked
Next/Back buttons don't work yet to go to the "CV and contacts" step

**Comment by mskmee** [comment]
This ticket about photo picker component. Test, please setting avatar image from library and camera with accepting critteries.

**Comment by ed9ward** [comment]
Tested
