### ISSUE TITLE
Create Sign In/Sign Up pages

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2023-bsa-talents#115]
The page should be cover Sign In and Sign Up for Talent and Employer. Check Miro for more info - https://miro.com/app/board/uXjVMwsyMQ4=/

![Image](https://user-images.githubusercontent.com/78347072/263462277-089cc379-3f82-4caf-8c20-97b8cbcb3638.png)

- [x] Sign In/Sign Up layout
- [x] Talent Routing
- [x] Employer Routing

P.S. Skip Google flow for this ticket

Acceptance criteria for the page "Sign Up":

- The page must contain the logo of platform in the upper left corner
- The page must contain  the fields to type the user’s Email and password
- The field for typing the user’s Email and password must be marked as required, marked *
- After the typing password the symbols change to *
- If a user leaves required fields empty, tips with information that this field is required appears
- The page must contain a radio button with the label “I’m hiring” and a radio button with the label “I’m looking for a job” for choosing the user’s role
- The page must contain the active button “Continue” to move to the next stage of registration
- The page must contain the button “I already have an account”
- The page must contain a Privacy Policy link and notification about the agreement with rules and policy

 Acceptance criteria for the page “Sign In” for Talent/Employer

- The page must contain the logo of platform in the upper left corner
- The page must contain  the fields to type the user’s Email and password
- The field for typing the user’s Email and password must be marked as required, marked *
- If a user types invalid data in the fields Email and/or password the notification about invalid Email or password appears on the screen
- If a user types invalid data in the fields Email and/or password these fields light red color
- If a user types invalid data in the field password the notification about the possibility of password recovery appears with the link to the page  to recover the password
- The page must contain the active button “Sing In” 
- The page must contain the active link “Forgot password”
- If a user leaves the required fields empty, these fields light red color
- If a user leaves required fields empty, tips with information that this field is required appears
- The page must contain  the checkbox with the label “Remember me”
- The page must contain active link “Sign Up”

**Comment by nikita-remeslov** [comment]
Sign-up will be with our layout but we will use form like this


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/78347072/1ea79020-4bda-420a-9ca3-980b4bbde3c2)

**Comment by JosuerBague** [comment]
> Sign-up will be with our layout but we will use form like this
> 
> ![Image](https://user-images.githubusercontent.com/78347072/263989936-1ea79020-4bda-420a-9ca3-980b4bbde3c2.png)

Do we want the radio buttons?

**Comment by nikita-remeslov** [comment]
@JosuerBague for sign-up yes

**Comment by Oleksandrra** [comment]
Created bug report https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/276
