### ISSUE TITLE
Create Talent Sign Up layout

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2023-bsa-talents#116]
![Image](https://user-images.githubusercontent.com/78347072/263462473-2d744b16-a677-480b-814a-b5ee0d8bd159.png)

- [x] Add Sign Up layout
- [x] Add steps
- [x] Add steps navigation (next, prev)

**User Story:**
As a user, I want to see a visible step counter representation, so that I can see my progress in the registration process.

**Acceptance criteria:**
- The page should have "Create an account to receive proposals" text on the top left
- The page should have "Let’s get started!" title and text below according to the design
- The page should have five steps below one another with the number of the step and its name:
1. Profile
2. BSA badges
3. Skills and projects
4. CV and contacts
5. Preview
- Current step should be visibly detached from others
- The page should have the current step counter (Step 01 / 05) in the same line as the current step name
- User should be able to navigate through steps with Next and Back buttons

**Comment by ed9ward** [comment]
Tested

**Comment by AllaBroshchak** [comment]
@ed9ward Please attach the screen
