### ISSUE TITLE
Change Mobile app icon

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#12]
Currently, we have default icons for the Android app:

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/103518438/9368247c-cfe9-4644-8c75-7a5217de016a)

We need to replace them with our app logo 
Logo can be found here: [https://www.figma.com/file/Yd7USgP7PLvA0W794jHXWu/BSA_recruting?type=design&node-id=5936-1272&mode=design&t=nf7ItsrLkZ6sdL2H-0](https://www.figma.com/file/Yd7USgP7PLvA0W794jHXWu/BSA_recruting?type=design&node-id=5936-1272&mode=design&t=nf7ItsrLkZ6sdL2H-0)

**Comment by anna9314** [comment]
Tested
