### ISSUE TITLE
Create chat list component

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2023-bsa-talents#125]
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/78347072/0e7b4e9d-6aca-4987-81da-eff00d151560)

**Comment by JemiJe** [comment]
[OUTDATED]
as I see, we have the same avatar element in 3 places on all chat page. and also on `Candidat's page_opened info`
so I propose make that sort of avatars as independent component (so we can reuse it in future), and folder  structure will be:
```
.
└── components/
    ├── page-avatar/
    ├── chat-list/
    │   ├── components/
    │   │   └── chat-item
    │   ├── chat-list.tsx
    │   └── .... 
    └── ...

```

**Comment by anna9314** [comment]
Tested
