### ISSUE TITLE
Create shared Modal component

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#127]
Create a shared Modal component. It should have a Material UI design style. It should be a window that can be closed on the backdrop and we can pass any options there.

**Comment by likeri29** [comment]
I should use this [library](https://www.react-native-material.com/docs/components/dialog) to create a modal or what do you mean by 'It should have a Material UI design style'

**Comment by katerynakostikova** [comment]
No, we'll create this component without any library, I mean that our custom component should match the Material design basic style/guidelines [https://m3.material.io/components/dialogs/overview](https://m3.material.io/components/dialogs/overview)
Material design basically is Google’s open-source design system so that each app have +- same style and is easy for users to understand
