### ISSUE TITLE
Create info about company in chat UI

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2023-bsa-talents#129]
User story:

As a talent, I want to be able to see a block with information about potential employers on the chat screen, so that I can find out about a company before I accept the contact

Acceptance criteria:

- Talent should be able to see a logo of a company, the full name of the employer, the job position of the employer
- Talent should be able to see a brief description of a company
- There should be a company link that talent can go to the company's website by clicking on it
- There should be the “Share your contact and CV” button
- When the talent hovers over the “Share your contact and CV” button, the button changes to blue color (like on the design)
- There should be the “The company already hired me” button, it should be underlined when hovering over it

![Image](https://user-images.githubusercontent.com/105710998/263659644-ae61dea0-2bf8-4b90-a2e6-c9a893247a67.png)

**Comment by anna9314** [comment]
Tested
