### ISSUE TITLE
Create Mobile app splash screen

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#13]
We need to research a library for adding a splash screen.  Discuss found variants with the team and implement it. The splash screen should have the App logo and BSA Talents under it. 
Logo can be found here: [https://www.figma.com/file/Yd7USgP7PLvA0W794jHXWu/BSA_recruting?type=design&node-id=5936-1272&mode=design&t=nf7ItsrLkZ6sdL2H-0]( https://www.figma.com/file/Yd7USgP7PLvA0W794jHXWu/BSA_recruting?type=design&node-id=5936-1272&mode=design&t=nf7ItsrLkZ6sdL2H-0)

**Comment by anna9314** [comment]
Tested


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/b44b4e62-8de7-4517-ac21-e81b2942e081)
