### ISSUE TITLE
Convert Token Service to Token Package

### ISSUE THREAD

**Issue by JosuerBague** [BinaryStudioAcademy/bsa-2023-bsa-talents#136]
Currently token service is defined here:
`backend/src/common/services`

We need to redefine it as a package:
`backend/src/common/token`

Follow style and structure from logger package:
`backend/src/common/logger`

After conversion, combine all packages into `package` dir with root file packages.ts:

- [x]  Convert token service to package
- [x]  Consolidate packages into package dir. `backend/src/common/packages`

**Comment by vladjsp** [comment]
First of all, great task description.
Should I also rename all token names that contain 'Service' word?
E.g. `class TokenServiceBase implements TokenService ` -> `class TokenPackageBase implements TokenPackage` etc. 
It seems to me that the 'Service' in the name is more descriptive, but I'm not sure.

**Comment by JosuerBague** [comment]
I think 'Token', 'TokenBase' would suffice. Since it will be relocated into packages dir, it will be understood that is a package.

Further with just Token usage would be cleaner, i.e: `Token.create()` | `Token.decode()'.
This will also align with the Logger package: `this.logger.info` | `this.logger.warn()`

That is my two cents though. If it is decided in the future that 'TokenService' should be used, then just push changes.
