### ISSUE TITLE
Add chat store

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2023-bsa-talents#150]
- [x] Add chat API
- [x] Add get messages action
- [x] Add create message action
- [x] Add add message action
- [x] Add join chat action
- [x] Add leave chat action

**Acceptance criteria:**

- User should be able to type and send a message
- User should be able to receive a message
- User should be able to join the chat with another user
- User should be able to leave a chat with another user
- Read message should have a “read” tick status
- Unread message should have an “unread” ticks status
- When a message is been typed the typing status should be displayed

**Comment by ed9ward** [comment]
Tested
