### ISSUE TITLE
Add chat endpoints

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2023-bsa-talents#151]
- [x]  Get all messages for chats (GET)
- [x]  Get all messages for chat (GET)
- [x]  Create message (POST)
- [x]  Read message (PATCH)
- [x]  Add model
- [x]  Add service
- [x]  Add repository
- [x]  Add migration

```js
const ColumnName = {
  ID: 'id',
  CREATED_AT: 'created_at',
  UPDATED_AT: 'updated_at',
  SENDER_ID: 'sender_id',
  RECEIVER_ID: 'receiver_id',
  CHAT_ID: 'chat_id',
  MESSAGE: 'message',
}
```

**Comment by Monyster** [comment]
@nikita-remeslov Question about CHAT_ID: 'chat_id' ?
I need to create table for chats, how should it look like?
For example, like this
```js
const ColumnName = {
  ID: 'id',
  NAME: 'name', 
  CREATED_AT: 'created_at',
  UPDATED_AT: 'updated_at',
};
```

Is there anything else to add, such as: "who starts the conversation", "isUnreadMessages", "isClosed", "isInArchive"?

And question about read message (PATCH). 
Do I need to add a column to chat_message table for this function?

**Comment by Monyster** [comment]
for current realization i made next
```js
const TableName = {
    CHAT_MESSAGES: 'chat_messages',
}

const ColumnName = {
    ID: 'id',
    SENDER_ID: 'sender_id',
    RECEIVER_ID: 'receiver_id',
    CHAT_ID: 'chat_id',
    MESSAGE: 'message',
    IS_READ: 'is_read',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
};
```

**Comment by anna9314** [comment]
Tested
