### ISSUE TITLE
Add logic to sign in flow

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#157]
We need to add logic for sign in flow: validation schema, request to the backend (can be mocked if now merged yet) and saving user data to the store. User token should be stored in phone's local storage. After user is signed in we need to check his/her role (Talent, Employer) and redirect to needed navigation (it should be refactored to support 2 roles)

**Comment by anna9314** [comment]
Tested
