### ISSUE TITLE
Add sign up flow

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#159]
We need to add UI and logic for sign up flow: validation schema, request to the backend (can be mocked if now merged yet). Saving user data to the sore will be implemented in this ticket: [https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/157]( https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/157). 
It'll have same fields as sign in but with different text and should also have this radio buttons (screenshot is just an example, colors should match our app): 

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/103518438/68b7628f-e389-480c-a6e7-8bbd69178b8d)

Acceptance criteria for "Sign Up":

- The page must contain the logo of platform from the top of the page in the middle
- The page must contain the fields to type the user’s Email and password
- The field for typing the user’s Email and password must be marked as required, marked *
- After the typing password the symbols change to *
- If a user leaves required fields empty, tips with information that this field is required appears
- The page must contain a radio button with the label “I’m hiring” and a radio button with the label “I’m looking for a job” for choosing the user’s role
- The page must contain the active button “Continue” to move to the next stage of registration
- The page must contain the button “I already have an account”
- The page must contain a Privacy Policy link and notification about the agreement with rules and policy

**Comment by illia-dobro** [comment]
Do you need to install a package radio button? Or use existing checkboxes?

**Comment by katerynakostikova** [comment]
Yes, we need radio buttons. Please investigate some libs and share them in the mobile channel (checkboxes are not ok, since we can select more than 1 when radio requires only 1)

**Comment by Oleksandrra** [comment]
@illia-dobro @katerynakostikova 

Description:
[Mobile]: The page contains a radio button without any label on the screen “Sing Up”

Environment:
 OS - Android
 Version - 12 SP1A.210812.016
Screen resolution 2400 x 1080
Severity Critical  (S2)

Steps to reproduce:

1. Open the app
2. Pay attention to the radiobutton under the field “Password”

Actual Result:
The page contains a radio button without any label on the screen “Sing Up”

Expected Result:
The page must contain a radio button with the label “I’m hiring” and a radio button with the label “I’m looking for a job” for choosing the user’s role
![photo1_b](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/ae3d51e4-2fe4-4f40-a2ca-396b252398ff)

**Comment by Oleksandrra** [comment]
@illia-dobro Still exists in my env, latest build 12.09.2023 10:51
Remove to - "In progress"

**Comment by illia-dobro** [comment]
Can you show a screenshot of the sign in page? Because on this page, not only are the radio buttons not shown, but the placeholders are also missing.

**Comment by Oleksandrra** [comment]
![Screenshot_2023-09-13-21-41-25-409_com bsa_talents](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/30dd4435-ca7f-4f84-8ae0-8367e40c6876)

**Comment by Oleksandrra** [comment]
![Screenshot_2023-09-13-21-43-01-089_com bsa_talents](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/7c92b63d-c926-45a9-9700-e16befe071b3)

**Comment by Oleksandrra** [comment]
The placement has changed, but title....

**Comment by Oleksandrra** [comment]
tested

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/ec6ac84c-cce2-4c51-8583-287835279592)
