### ISSUE TITLE
Create global styles

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#16]
Create global styles object with styles that will be used most often in the app (flex, flex-direction, etc.)

**Comment by anogire** [comment]
These should be styles for **screenOptions**, for example:
```
const darkScreenOptions = {
    navigationBarColor: '#1f1e29',
    statusBarColor: '#1f1e29',
    statusBarStyle: 'light' as const,
};

```
A **list of possible styles**, for example:
```
const styles = StyleSheet.create({
    root: {
        flex: 1,
        marginBottom: StatusBar.currentHeight,
    },
    container: {
        flex: 1,
        borderRadius: 9,
        backgroundColor: '#fff',
    },
    text: {
        fontSize: 16,
        color: '#222',
    },
    title (h2, h3, ...)
});
```

Or are these some kind of **wrapper styles** for existing styles? For example.
```
const styles = StyleSheet.create({
    root: {
        flex: 1,
    },
    flex-column: {
        flex-direction: column,
    },
    main-radius: {
        border-radius: 9,
    },...
});
```

**Comment by katerynakostikova** [comment]
@anogire Hello! Global styles should be located in `bundles/common/styles/global-styles.ts` and should look like this:

```
const globalStyles = StyleSheet.create({
	defaultScreenPadding: {
		padding: "some value",
	},
	flex1: {
		flex: 1,
	},
	flexDirectionRow: {
		flexDirection: 'row' as FlexStyle['flexDirection'],
	},
	justifyContentCenter: {
		justifyContent: 'center' as FlexStyle['justifyContent'],
	},
        .... 
});
```

This approach will help us to avoid creating lots of repeating `styles.ts` files and just reuse them from one object. For example for main screen views we'll just add style={[globalStyels.flex1, globalStyles.defaultScreenPadding]} instead of creating separate objects for each screen.

My advice is to add flex-related styles (justify, align and so on), global paddings and margins and in future we'll add text-related styles when we'll add custom fonts
