### ISSUE TITLE
Create chat page layout

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2023-bsa-talents#160]
**User story:**

As a talent, I want to have the chats page, so that I can communicate with potential employers.

**Acceptance criteria:**

- There should be the “Chats” name of the page in the upper left corner
- Chat screen should contain two parts: chat sidebar on the left side of the screen and main chat block
- The chat sidebar must include an input field for the search field on the top
- When the user chooses the search field it should be highlighted
- List of user’s chats should be displayed below the search field
- Every chat on the chat sidebar should be displayed with the user’s profile photo, user name, the last message and the last message time of delivery
- When the talent selects the chat it should be highlighted
- There should be a placeholder for the search field and the text area field
- There should be a chat page with messages in the middle with an input text area field at the bottom
- The text area field should be with the send message button
- Allowed length for text area – 1-5000 characters
- The user’s profile photo and user name should be displayed on the top of the chat page with messages

![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/72940c8a-801f-45af-b687-a3c68028878d)

**Comment by JemiJe** [comment]
we had task about company info [bt-129](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/pull/213), so where we should put that component in that case? or it won't be here? or it appears on click on company name, etc.?

**Comment by MChornomaz** [comment]
I have the same question)

**Comment by JemiJe** [comment]
it was wrong picture

**Comment by nikita-remeslov** [comment]
link PR

**Comment by anna9314** [comment]
Tested
