### ISSUE TITLE
Create Talent Sign up fourth step form

### ISSUE THREAD

**Issue by nika-sirak** [BinaryStudioAcademy/bsa-2023-bsa-talents#168]
- [x] Add to bundle components step4 form
- [x] On step4 form Next button data should be validated, use useAppForm() hook for this
- [x] After validation save data in state

**User story:**
As a talent, I want to be able to fill up a profile with my contact information, so that potential employers can access this info after contact happened.

**Acceptance criteria:**
- The registration step “STEP 04/05” is placed in the upper right corner on the same line with the title CV and contacts
- The fourth step must include input fields for Full name, Phone number, LinkedIn profile, Choose photo, and CV
- The Full name, Phone number, LinkedIn profile, and CV are required and have “*”
- Text inputs should have a placeholder
- Page must contain Choose photo button to add a photo
- Allowed image file is <5MB and could be only jpeg, png, jpg
- The Full name field should be between 3 and 50 characters in length and accept A-Z, a-z, (.), ('), (-), spaces
- The Phone number must start with "+" symbol at the beginning and allow up to 10 symbols total, digits 0-9 only
- Any other symbols in text fields or unsupported length, format should trigger the validation message appearance
- LinkedIn profile field accepts only links in the format of: https://www.linkedin.com/in/ + >0 symbols
- LinkedIn profile field length should be 30-250 chars and accept only: A-Z, a-z, 0-9, special chars
- Page must contain Choose file button to add a CV file to add a file from the device
- Allowed types for CV file should be docx, doc, pdf, max 5MB size
- Talent should be able to back to the previous step Skills and projects by clicking on the Back button
- Talent should be able to go to the next step Preview by clicking on the Next button. Only if no validation errors are present.
- Talent's information should be saved in the fields when switching between steps

**Comment by nika-sirak** [comment]
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/60103912/81133402-42b9-495e-9389-19d0f546cad5)

**Comment by ed9ward** [comment]
Added US\AC

**Comment by ed9ward** [comment]
Added BR to this step:
https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/356
Returned to In Progress until fixed
