### ISSUE TITLE
Create Talent Sign up third step form

### ISSUE THREAD

**Issue by lavandosya** [BinaryStudioAcademy/bsa-2023-bsa-talents#169]
- [x] Add to bundle components step3 form
- [x] On step3 form Next button data should be validated, use useAppForm() hook for this
- [ ] After validation save data in Store

![Image](https://user-images.githubusercontent.com/116720360/264077440-01d218c6-422c-4be6-8aa7-88b793d9ea98.png)

**User story:**
As a talent, I want to be able to fill up a profile with info about my skills, so that potential employers can evaluate my candidacy.

**Acceptance criteria:**
- Text “STEP 03/05” is placed in the upper right corner on the same line as the Skills and projects.
- The third step must include input fields:
1. Hard Skills (A-Z, a-z, special chars, spaces)
2. Level of English dropdown	(No English, A1 Elementary, A2 Pre-intermediate, B1 Intermediate, B2 Upper intermediate, C1 Advanced, C2 Proficiency)
3. I do not consider	checkboxes (Gambling, Dating, Gamedev, Crypto, Startups)
4. Preferred language of communication dropdown (English, Ukrainian, Russian, Spanish, Portuguese, French, German, and Chinese (Mandarin))
5. Project link URL (5-50 symbols, A-Z, a-z, 0-9, special chars). User can add up to 5 links.
- The Hard Skills, Level of English, I do not consider, Preferred language of communication are required and have “*”
- Text inputs and dropdowns should have a placeholder
- Any other symbols in text fields or unsupported length, format should trigger the validation message appearance
- Talent should be able to back to the previous step BSA badges by clicking on the Back button
- Talent should be able to go to the next step CV and contacts by clicking on the Next button. Only if no validation errors are present.
- Talent's information should be saved in the fields when switching between steps

**Comment by ed9ward** [comment]
Added US\AC

**Comment by ed9ward** [comment]
Pulled new changes hour ago and got no third step.

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/5f34f266-7911-4bb1-8968-701ed9c84bdc)

**Comment by ed9ward** [comment]
- Talent's information should be saved in the fields when switching between steps 

This hasn't been implemented yet

**Comment by ed9ward** [comment]
Added BR to this step:
https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/350
Returned to In Progress until fixed
