### ISSUE TITLE
Create app theme

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#17]
Create a basic app theme with app colors and apply it to shared components
Design link: [https://www.figma.com/file/Yd7USgP7PLvA0W794jHXWu/BSA_recruting?type=design&node-id=0-1&mode=design&t=Q2BWnU8ikNDNZ3Oh-0](https://github.com/orgs/BinaryStudioAcademy/projects/17/views/url)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/103518438/80f72baa-fc14-4ce6-84b1-bbfe99f1ff6a)

**Comment by illia-dobro** [comment]
Hello!

Where should we take colors from? Components or Colors? There is some difference. Also, is path bundles/common/theme/colors.ts okay?

Applying it to shared components. However, these components are still in progress. How can I apply it to them?

**Comment by katerynakostikova** [comment]
@illia-dobro Hello! You can find all app colors in the design (see screenshot in ticket). If you click on a color item in Figma there will be a color name and value. 

Let's keep colors in `bundles/common/styles/colors.ts`. If components tasks will be merged before your task, you'll add them, if after, others will apply them.
