### ISSUE TITLE
Add wrapper for sign in/up screens

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#193]
Currently we have only form UI for sign in/sign up, since we already have App logo we can complete the UI for these screens
Design link: [https://www.figma.com/file/Yd7USgP7PLvA0W794jHXWu/BSA_recruting?type=design&node-id=4266-1041&mode=design&t=fyH0m4tlKerCXYlp-0](https://www.figma.com/file/Yd7USgP7PLvA0W794jHXWu/BSA_recruting?type=design&node-id=4266-1041&mode=design&t=fyH0m4tlKerCXYlp-0)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/103518438/48c0fd8b-bb93-4b79-af17-24261c96d597)

**Comment by anna9314** [comment]
Tested
[BUG] The layout of the Sign in page does not correspond to the approved design #318
