### ISSUE TITLE
JWT Auth

### ISSUE THREAD

**Issue by MaksymGavatuk** [BinaryStudioAcademy/bsa-2023-bsa-talents#20]
Implement JWT auth singing + verification
Use please jose lib: https://www.npmjs.com/package/jose
 - [x] JWT token generated
 - [ ] JWT token returning for sign-in and sign-up endpoints
 - [x] JWT token stores info about user_id
 - [x] JWT token is stored on localStorage

**Comment by JosuerBague** [comment]
I am not sure how to implement JWT for sign-in. Should I wait for bt-19?

I will open a draft pull request.

**Comment by nikita-remeslov** [comment]
Sign-in you can skip
