### ISSUE TITLE
Create the "Has the employer already hired you?" block on the chat page

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#203]
**User story:**
As a talent, I want to be able to confirm the hiring, so that I can notify admin that I've got the offer.

**Acceptance criteria:**
- There should be a block on the chat screen with the “Has the employer already hired you?” title, “Yes” and “No” radio buttons and the “Submit” button below (like on the Candidate's page)
- When a talent clicks on the “Submit” button, the confirmation window should appear
- The "Are you sure you want to confirm this action?" confirmation window should have "Yes" and "Cancel" buttons
- When the talent hovers over the “Submit” button, it should be highlighted in blue (like on the design)

![Image](https://user-images.githubusercontent.com/63346295/264720425-f9309a27-114b-46db-bc2e-8db95dcb7102.png)

**Comment by JosuerBague** [comment]
I guess this ticket waits on this one? [Chat Layout](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/160)
