### ISSUE TITLE
Secure Endpoint Routing

### ISSUE THREAD

**Issue by MaksymGavatuk** [BinaryStudioAcademy/bsa-2023-bsa-talents#21]
Implement private and public endpoints logic

- [x] Add authorization plugin for routes
- [x] Inject signed current user to request (if token is valid)
- [x] Add white (public) routes. For now: sign-in, sign-up only

**Comment by JosuerBague** [comment]
Hello, to clarify:

Task 1 & 2: Are backend while Task 3 is fronted routing?

**Comment by nikita-remeslov** [comment]
No, it is all a Backend task. We should add white routes on the backend. We should have access to white routes without token

**Comment by JosuerBague** [comment]
Hello, am I correct in thinking that I should wait for bt-20? This task requires tokens which will be implemented in bt-20.

**Comment by nikita-remeslov** [comment]
Could you create PR with your code?

**Comment by MaksymGavatuk** [comment]
Yes, you're right. But you can push your code for review, and after finishing task 20, you will finish current task.

**Comment by nikita-remeslov** [comment]
@JoshDagat  Link PR to the Issue, please

**Comment by JosuerBague** [comment]
I have a token verification helper in bt-20. Should I move that here or keep it in 20?

**Comment by MaksymGavatuk** [comment]
If you need helper from task-20, merge this branch to current branch. And use helper in this branch, but leave description in this PR, that this PR contains changes from task-20. And we firstly merge task-20 and after that merge this PR.

**Comment by JosuerBague** [comment]
Just to clarify, merge bt-20 to bt-21, correct?

**Comment by JosuerBague** [comment]
Hello, a question for 2nd task in this ticket:

- Inject signed current user to request (if token is valid)

Is it enough to just return the id and email?

**Comment by MaksymGavatuk** [comment]
I think it will be enough, or we can expand it in the future. For now { id: string, email: string } enough
