### ISSUE TITLE
Add Dropdown common component

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2023-bsa-talents#214]
https://mui.com/base-ui/react-menu/

- [x] add common component
- [x] update header to add Sign out functional

Acceptance criteria for Dropdown common component

- Clicking on a closed field opens a menu of options
- Field containers should vertically align with other form components on a page
- A Dropdown open down 
- To select an option the user can click anywhere inside an option container
- Selecting an option from the menu closes it and the selected option text replaces the placeholder text in the field and also remains as an option in place if the menu is open
- Click outside of the option container closes it, and the field stays empty

Acceptance criteria for Sign out component

- after clicking on the registered user's avatar, a dropdown list appears
- dropdown list contains an option to Sign out
- criteria of the dropdown list “Sign out” is the same as the common component criteria
- after choosing “Sign out” the user is redirected to the page “Sign In”, the user is not logged in

**Comment by Oleksandrra** [comment]
tested
