### ISSUE TITLE
Profile layout

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2023-bsa-talents#215]
It should be reusable.

- [x] Check the design and define all places where we can use 
- [x] Add a comment to the ticker where we can use it
- [x] Add candidate layout

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/78347072/d88edcaa-3ba9-4d7d-b6f3-d82e8f5e98ee)

User story:
As a Talent, I want to be able to see my profile, so that I can read/review all information that I filled in the registration fields

Acceptance criteria for page“Step 05/05 of Sign Up”

1. The content area of the page must contain:

- the information about the job title that the user chose
- the BSA badges with labels and scores that the user chose
- the information about the skills that the user chose
- the information about the preferred language that the user chose
- the user’s cover letter
- the information about the user’s project which includes: an image, repository link button
- the active button “Save without publishing” and the active button “Publish now”

2. The sidebar of the page must contain:

- the information about the size of salary expectation that the user chose
- the information about the current location that the user chose
- the information about the years of experience that the user chose
- the information about the English level that the user chose
- the information about the employment type that the user chose
- the information about the vacancies that the user does not consider

3. The layout must match the design posted on Figma https://www.figma.com/file/Yd7USgP7PLvA0W794jHXWu/BSA_recruting?type=design&node-id=4262-3412&mode=design&t=zTmXnMsDWkBBWqHG-4 
_____________________________________________________________

User story:
As an Employer, I want to be able to see Talent profile, so that I can review basic information and make decision about the contact with Talent

Acceptance criteria for page “Candidate’s page_closed info”

1. The page must contain the breadcrumb trail links
2. The content area of the page must contain:
- the information about Talent's job title  
- the Talent's BSA badges with labels and score
- the information about the Talent's skills
- the HR comments about the Talent's skills
- the information about the Talent's preferred language
- the Talent's cover letter
- the Talent's project which includes: an image, repository link button
- the active button “Contact candidate”
- the information about the size of the Talent's salary expectation
3. The sidebar of the page must contain:
- the  information about the Talent's current location
- the Talent's years of experience
- the Talent's English level
- the Talent's employment type
- the vacancies that the Talent  does not consider
- the information about the Talent's date account publishing
- the active button “Contact candidate”

4. The layout must match the design posted on Figma
https://www.figma.com/file/Yd7USgP7PLvA0W794jHXWu/BSA_recruting?type=design&node-id=4854-1558&mode=design&t=zTmXnMsDWkBBWqHG-4 
_______________________________________________________

User story:
As an Employer, I want to be able to see Talent profiles with full information, so that I can contact Talent and make decision about the hiring

Acceptance criteria for page  Candidat's page_opened info

1. In addition to the information indicated on the page “Candidate’s page_closed info”, the sidebar of the page  "Candidate's page opened info" must contain
- the information about the Talent’s email
- the information about the Talent’s phone number
- the radiobutton: label “Have You hired a candidate”, options ‘Yes”, “No”
- the active button “Submit” under radiobutton

2. The layout must match the design posted on Figma
https://www.figma.com/file/Yd7USgP7PLvA0W794jHXWu/BSA_recruting?type=design&node-id=4854-1558&mode=design&t=zTmXnMsDWkBBWqHG-4

**Comment by Simpsonkk** [comment]
Candidat's page_closed info, Candidat's page_opened info, step 5 on sign up talent page, probably candidates card on search employer page but then should add  a lot of conditions inside component because of which the styles will change

**Comment by Oleksandrra** [comment]
@nikita-remeslov Are US and AC for step 5 needed  in this ticket?

**Comment by nikita-remeslov** [comment]
@Oleksandrra yes

**Comment by Oleksandrra** [comment]
tested
