### ISSUE TITLE
Add Contact candidate modal

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2023-bsa-talents#216]
**User story:**
As an employer, I want to be able to contact a candidate, so that I can send information about a potential job.

**Acceptance criteria:**

- When an employer clicks on the “Contact candidate” button on the Candidat's closed page, the modal window should appear.
- The modal window must include input fields for “Add link to the vacancy”, “Write a message”
- The Add link to the vacancy”, “Write a message” fields should have the placeholder
- “Add link to the vacancy” field accepts only links in the format of: www. OR http:// OR https:// + >0 symbols + "." + >0 symbols
- “Add link to the vacancy” field length should be 5-250 chars and accept only: A-Z, a-z, 0-9, special chars
- Employer should be able to add more links, by clicking on “+Add more link”
- Employer should be able to add up to 5 links
- Employer should be able to delete added links by clicking on the delete icon
- “Write a message” field must be required and have “*”
- “Write a message” field length should be 10-5000 chars and accept A-Z, a-z, 0-9, special chars, spaces
- The modal window must include “Save as template” checkbox
- When the employer chooses the “Save as template” checkbox, the field for adding the template name should appear
- When the employer opens the “Contact candidate” modal window next time, it should be a list of saved templates for the user to choose from, a if template was saved
- The template name field should have the "Template name" placeholder
- Employer should be able to edit the name of template and delete template
- There should be edit and delete buttons right of the template name field
- The modal window must include the “Send message” button to send information to the talent

![Image](https://user-images.githubusercontent.com/78347072/265203539-a8811313-a6a6-4b6f-86d3-cc221fefe121.png)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/1b4f3ba4-c8f1-4d13-801d-ca756863ae32)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/6336e38d-4087-431a-a1c2-d9b7df875dec)

**Comment by ptarho** [comment]
@anna9314  Can you please elaborate on the templates list screen? It's not particularly clear how an employer can contact a candidate without using one of the existing templates? The fullscreen, not cropped screenshots showing how the whole template list modal would be much appreciatedImage

**Comment by anna9314** [comment]
Unfortunately, I do not have full screenshots, if necessary, I will ask PO tomorrow to send it
As I understand it, if you select the checkbox "save as a template", the next time you open a modal window, this template should be displayed like on the screenshots. It should work like on Djinni 
When the user clicks on a template, the text of the template will appear in the message field
The user can write a new message without using templates, just write and click on the Sent button

Screens from djinni:
![Screenshot_7](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/31d18a61-969c-4c2f-818d-3472956fd9f2)
![Screenshot_6](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/a2607152-191d-435f-b605-3353fa7f1580)

**Comment by ed9ward** [comment]
Tested
