### ISSUE TITLE
Connect SignUp to API

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2023-bsa-talents#220]
Connect UI to API

User story
As a Talent, I want to Sign Up for BSA hiring platform, so that can create my personal account on the platform for looking for a job

Acceptance criteria:

- If the fields Email and Password are empty, these fields light red color, and tips with information that this field is required appear, the user stays on this page
- After entering invalid data (does not match validation requirements) the notification about an invalid Email or Password appears on the screen, these fields light red color, and the user stays on this page
- If the user enters  Email and Password that was before used, the notification “User exists” appears, the user stays on this page
- After clicking on the button  “Continue” the user who chooses “I’m looking for a job” is redirected to the step “01/05” page of Onboarding Talent Flow
- Clicks on the button "I already have an account” redirects to the page "Sign In"

User story
As an Employer, I want to Sign Up for BSA hiring platform, so that can create my personal account on the platform to look a employees

- After clicking on the button  “Continue” the user who chooses “I’m hiring” is redirected to the Onboarding  Employer Flow
- Other points are the same as Talent’s role

**Comment by nikita-remeslov** [comment]
Use the PR as base - https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/pull/153

**Comment by savinaDaria** [comment]
already in PR  base - https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/pull/153

**Comment by Oleksandrra** [comment]
@savinaDaria 

Description:
The user who chooses “I’m looking for a job” stays on the page “Sign Up” after clicking on the button “Continue” 

Environment:
 OS - Windows
 Browser - Google Chrome
 Version - 116.0.5845.142

Severity Blocker (S1)

Steps to reproduce:

1. Open the page http://localhost:3000/sign-up
2. Enter the valid Email in the field “Email”  (fovoray111@vikinoko.com)
3. Enter the valid password in the field “Password” (Fovoray315@)
4. Choose radiobutton “I’m looking for a job”
5. Click on the button “Continue”
6. Pay attention that the user stays on the page “Sign Up”
7.
Actual Result:
The user who chooses “I’m looking for a job” stays on the page “Sign Up” after clicking on the button “Continue” 

Expected Result:
After clicking on the button “Continue” the user who chooses “I’m looking for a job” is redirected to the step “01/05” page of Onboarding Talent Flow

Attachment https://drive.google.com/file/d/1EwTjYFAWzxbwFFbDWLqJd6YD-UWIThY3/view?usp=drivesdk
