### ISSUE TITLE
Click on the BSA logo on every page should lead to the main page

### ISSUE THREAD

**Issue by ed9ward** [BinaryStudioAcademy/bsa-2023-bsa-talents#222]

**Comment by ed9ward** [comment]
Need to add redirection on click on the 404 page and Sign In Sign Up pages

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/adaeb1ad-efc4-4c36-83c5-d3e0464c8a74)

**Comment by vladjsp** [comment]
@ed9ward  fixed in https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/pull/264/commits/0cd1b5d4e1a7e3939b67f367f2008bd24f01ee5b
