### ISSUE TITLE
Combine talent onboarding layout with forms

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2023-bsa-talents#224]

**Comment by ed9ward** [comment]
If you navigate pages through browser > < back, next buttons - current step counter breaks and shows wrong number and title of step.

So I'll return this ticket to further work cause it's not working now as expected. 


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/6fcf99a5-cb31-45ee-ad7a-e36b267d0dc7)

**Comment by ed9ward** [comment]
Steps layout disappears after navigation with a browser back button from the 4th step.
![Image](https://user-images.githubusercontent.com/8355821/266609138-eae82afb-7794-4a89-a548-1df5abd72fc2.png)
