### ISSUE TITLE
Connect SignIn to API

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2023-bsa-talents#232]
User story:

As a Talent, I want to Sign In to BSA hiring platform, so that can use all the functionalities as a registered user for looking for a job

Acceptance criteria:

- If the Talent enters the Email and Password used for registration and clicks Login is redirected to the page “Chat”
- If the fields Email and Password are empty, these fields light red color, and tips with information that this field is required appear, the user stays on this page
- After entering invalid data (does not match validation requirements) the notification about an invalid Email or Password appears on the screen, these fields light red color, and the user stays on this page
- If entered Email and Password are not before used the notification “User does not exist” appears, Talent stays on this page
- If the data in the field Password are invalid the notification about the possibility of password recovery appears with the link to the page  to recover the password
- Click on the button “Forgot password” opens the page to recover the password 
- Click on the link “Create an account” redirects to the page “Sign Up”

User story:

As an Employer, I want to Sign In to BSA hiring platform, so that can use all the functionalities as a registered user for hiring employees

Acceptance criteria:

- After entering Email and Password used for registration and  clicking Login the Employer is redirected to the page “Search”
- Other points are the same as Talent’s role

**Comment by anna9314** [comment]
@vladjsp [BUG] User is redirected to the onboarding steps after clicking on "Forgot Password?" #311
https://github.com/orgs/BinaryStudioAcademy/projects/17/views/1?filterQuery=&pane=issue&itemId=37983469

**Comment by anna9314** [comment]
@vladjsp  Is the functionality ready when the user is redirected to the chat page after logging in?
Because I've got this:


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/338f92d1-ba2d-4b87-a7e2-1303c1526bd4)
