### ISSUE TITLE
Refactor className usage

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2023-bsa-talents#233]
for class names, we should use camelCase

- [ ] update selectors
- [ ] update all components

usage
```js
className={getValidClassNames(style s.logo, styles.color)} // combine few classes
className={styles.color} // single class
className='container' // gloval class
```

**Comment by JosuerBague** [comment]
For more than one global classNames should I combine using getValidClassNames?
```
className={getValidClassNames('input-container', 'email')}
```
or
```
className='input-container email'
```

**Comment by JosuerBague** [comment]
What about styles that follow MUI convention?


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/90120572/04d11621-7b90-4637-bcbc-e71b5669d56e)
