### ISSUE TITLE
Fix structure

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2023-bsa-talents#235]
1.
![Image](https://user-images.githubusercontent.com/78347072/265541362-fcb255bc-f59a-42b5-9ff5-6cb257318709.png)

```
radio
 - component
    -- // all components
 - radio.ts
```

2.
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/78347072/01605680-eb5f-46df-b4be-ebf1661fde2c)

**Comment by JosuerBague** [comment]
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/90120572/daa4882a-7ec0-4d40-ad70-d77f36d56fcc)

**Comment by JosuerBague** [comment]
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/90120572/186697f3-3642-4200-b2aa-9f0555eca51e)

**Comment by JosuerBague** [comment]
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/90120572/8ea42792-0af9-44b0-8427-4ea50bdd391a)
