### ISSUE TITLE
Pass rest properties

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2023-bsa-talents#236]
frontend/src/bundles/common/components/form-control-label/form-control-label.tsx
frontend/src/bundles/common/components/form-control/form-control.tsx
frontend/src/bundles/common/components/checkbox/checkbox.tsx

Not all props are attached to the component

**Comment by JosuerBague** [comment]
Checbox had props passed already so I didn't touch:

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/90120572/3913d90d-0b97-4db0-88b5-4438420bd0fb)
