### ISSUE TITLE
Add logic for Onboarding Drawer navigation

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#246]
Currently, users can access any onboarding step in the navigation. We need to change UI and behaviour depending on the data that we have.

**User story:**
As a talent,  I want to have a timeline, so that I can keep track of the progress of filling out the profile

**Acceptance criteria:**

- Each step of the timeline should have 3 states: disabled, active, and completed
- When the talent moves on to fill in a new step, the indicator should be displayed as active and visually highlighted
- Active state should automatically progress to completed state when the talent completes the required fields of the step
- Users should not be able to interact with or click on a disabled step.
- The disabled step indicator should be grayed out

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/103518438/be74af04-0eb4-47a7-8445-2f108014a255)

**Comment by anna9314** [comment]
[BUG] Progress bar is not displayed in blue color when step is completed #428
https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/428
