### ISSUE TITLE
Create file upload endpoint

### ISSUE THREAD

**Issue by MaksymGavatuk** [BinaryStudioAcademy/bsa-2023-bsa-talents#250]
We need to create endpoint to upload our files in the system connected with AWS S3 bucket
- [x] create account on AWS S3 bucket
- [x] create fileStorage package to upload file to AWS S3 (AWS keys to .env and update .env.example) 

  **BUT DON'T PUSH YOUR KEY TO GIT HUB!!!** 

- [x] create file repository 
- [x] create file service
- [x] create file controller

**Comment by JosuerBague** [comment]
Made preliminary fileStorage package with upload method:


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/90120572/1a2912be-98c5-4cd3-964a-0f91820dcba0)


Managed to upload to S3:


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/90120572/d9a19b1f-3c7b-4b07-a484-482496d1a9b1)


But can't access file yet:


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/90120572/acc48126-0fc2-49be-a09a-959b05adda0b)


Will investigate further.

**Comment by JosuerBague** [comment]
@MaksymGavatuk  If I'm uploading the file, does the flow go:

1) Upload file to S3.
2) Get details from S3 Object.
3) Store details in repo as File Entity?

**Comment by MaksymGavatuk** [comment]
Upload should take not filePath but file: Buffer;

**Comment by MaksymGavatuk** [comment]
Make bucket to private field of class

**Comment by ed9ward** [comment]
Blocked until https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/335 merged

**Comment by anna9314** [comment]
tested
