### ISSUE TITLE
Create endpoint to search users

### ISSUE THREAD

**Issue by MaksymGavatuk** [BinaryStudioAcademy/bsa-2023-bsa-talents#251]
Create search endpoint for employer
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/93519384/22fb4d36-9fbd-417a-afc0-5428ebabcc73)

- [x] create DTO types
- [x] create request in repository
- [x] create method in service
- [x] create GET endpoint
- [x] add filters as query params to request

Acceptance criteria:

1. Employers can choose the kind of search
- If an Employer chooses a basic search he/she can use the profile name of Talent. After sending the query, as result will return the Talent’s cards, where the profile name corresponds to the one entered in the search query
- If an Employer chooses a full-text search he/she can use any criteria, that describe Talent. As a result  will return all strings containing the word from the search query

2.When the Employer presses “Dandruff” the search query is sent

3. When the Employer chooses the filter “Active Talent search only” as result will return the Talent’s cards, that chose those criteria in their profile info.

4. When the Employer chooses the value in the filter as result will return the Talent’s cards, that contain the chosen value in the Talen’t profile info. The Employer can choose several values in this dropdown component. If that happens as result will return Talent’s cards, which contain all chosen values or at least one of them. These rules apply to all of the filter fields.

5. When the Employer chooses the value in several filters or several values of the one filter as result will return Talent’s cards, which contain all chosen values or at least one of them.

6. When the Employer presses the button "Reset all filters" all chosen values in the filters disappear and the dropdown component returns to the default state

7. When the Employer uses search without any filters as result will return the Talent’s cards, which contain entered in the search query value

8. The Employer can sort search result by salary, experience,date of user registration (newest/oldest)

- When the Employer chooses the option to sort by salary in ascending order as a result Talent’s cards, which appear in search results, sort by ascending order of value salary expectation that the Talent chose when filling out the profile
- When the Employer chooses the option to sort by salary in descending order as a result Talent’s cards, which appear in search results, sort by descending order of value salary expectation that the Talent chose when filling out the profile
- When the Employer chooses the option to sort by experience in ascending order as a result Talent’s cards, which appear in search results, sort by ascending order of value experience  that the Talent chose when filling out the profile
- When the Employer chooses the option to sort by experience in descending order as a result Talent’s cards, which appear in search results, sort by descending order of value experience  that the Talent chose when filling out the profile
- When the Employer chooses the option to sort by newest as a result Talent’s cards, which appear in search results, sort by ascending order of value date of user registration
- When the Employer chooses the option to sort by oldest as a result Talent’s cards, which appear in search results, sort by descending order of value date of user registration

9. If the search by the selected filters or the entered search query did not give a result, the message "No results to display" is returned
10. Talen’s cards, which appear in search results are active. After clicking on chosen Talent's card it opens fully

**Comment by Oleksandrra** [comment]
![des_пошук](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/b4403808-0cdf-428b-9985-9909bff32075)

**Comment by Oleksandrra** [comment]
https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/754

**Comment by Oleksandrra** [comment]
tested
