### ISSUE TITLE
Add Terms and Conditions to the Sing up page

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#254]
**Acceptance criteria:**

- The "I agree to the BSA Talents Terms" checkbox must be on the Sing up page
- “BSA Talents Terms” must be a clickable link that opens a new page displaying the complete terms and conditions document.
- The checkbox must default to an unchecked state
- Users must be unable to proceed with the sign-up process unless they check the " I agree to the BSA Talents Terms " checkbox.
- An error message should be displayed if a user attempts to sign up without checking the checkbox, prompting them to accept the terms before continuing.

![Image](https://user-images.githubusercontent.com/63346295/265682681-d665161c-45e8-49dd-82d6-64ad362272c5.png)

**Comment by vladjsp** [comment]
@anna9314 @nikita-remeslov 

Here is how our sign up form looks like.
![Screenshot 2023-09-05 at 16-36-10 Vite React TS](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/118971905/32cd193a-5a1a-4073-b6f8-04595958c2b9)

A few questions.
1. Should this check box be visible to both the talent user and the employer user, or only to talents?
2. Is the position of the checkbox showed correctly on the picture?
3. Do we already know destination url for BSA Talents Terms?
4. Should I leave the Privacy Policy where it is shown in the picture?

**Comment by nikita-remeslov** [comment]
1. Only for the talent
2. In design we don't have Privacy Policy
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/78347072/fb14df78-272b-4b7d-8e3c-673f7f84150f)
3. TBD. Just a placeholder for now
4. It is different information. We should keep both

**Comment by ed9ward** [comment]
Tested
