### ISSUE TITLE
Create Onboarding step2 - BSA badges

### ISSUE THREAD

**Issue by savinaDaria** [BinaryStudioAcademy/bsa-2023-bsa-talents#257]
- [ ] Add to bundle component bsa-badges-step 
- [ ] On Next button data should be validated?, use useAppForm() hook for this
- [ ] After validation save data in the Store

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/58756139/f008a002-4f74-477c-b4fd-ff7b41de0465)

**User story:**
As a talent, I want to be able to choose and add badges to my profile, so that potential employers can get familiar with my soft skills

**Acceptance criteria:**
“Your average project score”, “Your average lectures score”, “Level of English” should be chosen by default and talent can’t change it
Talent should be able to choose only “Communication score”, “Working with team score”, “Punctuality” badges
Talent should be able to choose several badges
Talent should be able to go to the next step without choosing badges
Talent should be able to back to the previous step "Profile" by clicking on the “Back” button
Talent should be able to go to the next step "Skills and projects" by clicking on the “Next” button
Talent 's information should be saved in the fields when switching between steps

**Comment by ed9ward** [comment]
@savinaDaria Take a look, is this enough AC for you to understand and proceed with this task?

**Comment by savinaDaria** [comment]
@ed9ward As I understand types of badges we will store in DB(bsa_badges) because they can extend, so I think we should add **isDefault**(boolean) column to DB to verify whether it should be selected by default at this step. 
Checking for several badge type names in code (“Your average project score”, “Your average lectures score”, “Level of English”) is a bad practice I think

**Comment by ed9ward** [comment]
Sound like a nice solution to me, but I'm not a BE dev, so these questions should be discussed and approved with them)
