### ISSUE TITLE
Create employee search page

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2023-bsa-talents#258]
![Image](https://user-images.githubusercontent.com/105710998/265746999-76fcd42c-d989-4669-a955-50c721a39ae6.png)

Also create a store for searching with filters since we will filter employees on backend

Acceptance criteria:

1. The content area of the page must contain:
- search field for typing search requests. This field must have a button for sending search request
- the radiobuttons with title "basic search" and title "full-text search" under the field "Search"
- dropdown component for sorting search results with option by salary in ascending order, salary in descending order, experience in ascending order, experience in descending order , newest , oldest under the field "Search"
- cards of candidates, that display as search result

2. The sidebar of the page  must contain:
- section header “Filters”
- button “Reset all”
- checkbox with the label “Active searching talents only”
- dropdown component with the label “Job title”
- dropdown component with the label “Years of experience”
- dropdown component with the label “Hard skills”. The selected components are displayed as tags
- dropdown component with the label “BSA characteristics”
- dropdown component with the label “BSA badges”
- dropdown component with the label “BSA project name”
- dropdown component with the label “Location”
- all dropdown components are multichoice
- radiobutton with the label “Level of English” with options: A1, A2, B1, B2, C1, C2
- checkbox with the label “Employment type” with options: Full-time, Part-time, Remotely, Freelance, Relocation to another country

**Comment by vladjsp** [comment]
@Oleksandrra 
1. Do we really need a search button because we don't have it in the design. We can return search results when the user types.
2. Radio group for English level looks too strict because the employer can choose only 1 option. It may be better to use the checkboxes as for the employment type, as the logic of these two filters is very similar.

**Comment by Oleksandrra** [comment]
@vladjsp
1.  I clarified this with PO - some button should be there. We can make just some sign indicating "Search", without letters, I think it will be Dandruff (like on screen) 
2. Do You think user can have a few levels of knowledge language?

**Comment by vladjsp** [comment]
@Oleksandrra 
ii. But it's not about the level of the user's English, but about the filters. If HR doesn't matter the user has B1, B2 or C1, now they have to do 3 searches to see all candidates, first with B1, then B2 and that with C1 radio button. But with checkboxes HR will see all users with B1, B2 and C1 english at once.

**Comment by Oleksandrra** [comment]
Yes, my bad. Better do checkbox.

**Comment by vladjsp** [comment]
For now:
1. The task is to create a controlled input component for the search field and store value in the store.
2. Create store for filters and search values.

**Comment by vladjsp** [comment]
@Oleksandrra 
Hi.
What values ​​should the Years of Experience dropdown list contain?
Like:
- without experience
- from X to Y
- more that X
- X
- Y
- Z years
- < Q years
- > W years
etc.


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/118971905/fc0692df-402e-4160-a868-be52798cb94d)

**Comment by Oleksandrra** [comment]
@vladjsp @savinaDaria 
 update about sorting 
![IMG_20230914_095201](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/6a392056-ac74-4f36-90ae-3b2052c4cce6)
![sort](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/724eaf49-a871-49db-92f9-f001b1c7c2e5)

**Comment by anna9314** [comment]
Tested
