### ISSUE TITLE
[BUG] The “Return to main” link is cut off on the “Not found” page

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#263]
**Description:**
The “Return to main” link is cut off on the “Not found” page when the screen height is less than 755 px

**Preconditions:**
The localhost is open

**Environment:**
OS Windows 11 
Google Chrome 116.0

**Steps to reproduce:**
1. Open the "Not found" page
2. Choose resolution 1536 x 739px
3. Pay attention to the “Return to main” link

**Actual Result:**
The “Return to main” link is cut off on the “Not found” page when the screen resolution is 1536 x 739px

**Expected Result:**
The “Return to main” link is fully visible

**Visual Proof (screenshots, videos, text):**
![Screenshot_2](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/d4df0381-e4c3-4c19-aea1-5909e2445e3a)
![Screenshot_3](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/6bdd91bd-dc56-4526-9b98-fd0c05e3af2d)

**Severity:**
Minor (S4)

**Comment by ed9ward** [comment]
Tested

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/77b2dbf2-4dd8-433f-aef8-b33468ee199e)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/f652eddc-d020-4141-adbd-f1379c3f8984)
