### ISSUE TITLE
Create Candidates screen

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#266]
**User story:**
As an employer, I want to have a search page, so that I can find a potential candidate.

**Acceptance criteria:**

- There should be the “Candidates” name of the page in the left upper corner
- There should be an indicator of the number of candidates on the left side of the “Candidates” name
- The search page must include the input search field
- The search field must have a placeholder
- When the employer chooses the search field it should be highlighted
- There should be the “Filters” button on the left side of the search field
- List of candidates' cards should be displayed below the search field
- Candidate card should display profile name, location, years of experience, level of English, date of publishing the profile, salary expectation
- Candidate card should display chosen BSA budges, selected hard skills, a brief description of the candidate
- Candidate card should have the “Read more” button

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/99a4589c-cb23-44c6-b00d-40d7bbb795f7)

**Comment by anna9314** [comment]
Tested
