### ISSUE TITLE
Create Slider component

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2023-bsa-talents#27]
![Image](https://user-images.githubusercontent.com/78347072/261956118-2f2f42e9-6167-4f45-b2da-62529fe76b8a.png)

https://mui.com/material-ui/react-slider/

**Comment by JemiJe** [comment]
should I put Slider inside Box and any customer pass styles to that Box (for instance width etc.). or I just leave it raw Slider that customer put it in anything in future (with proper props of course).

**Comment by nikita-remeslov** [comment]
I think you should make something like this 
https://mui.com/material-ui/react-slider/#label-always-visible
