### ISSUE TITLE
Connect Talent Onboarding to API

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2023-bsa-talents#274]
**Acceptance criteria:**

- [x] - After clicking on the “Continue” button on the Sign up page, talent who chooses “I’m looking for a job” is redirected to the step “01/05” page of Onboarding Talent Flow.

- [x]  - When the Talent fills in all required fields on the “Profile” step and clicks on the “Next” button is redirected to the “BSA badges” step

- [x] - Talent can choose badges (“Your average project score”, “Your average lectures score”, “Level of English” is chosen by default) on the “BSA badges” step  or click on the “Next” button and talent is redirected to the “Skills and Projects” step

- [x] - When the Talent fills in all required fields on the “Skills and Projects” step and clicks on the “Next” button is redirected to the “CV and Contacts” step

- [x] - When the Talent fills in all required fields on the “CV and Contacts” step and clicks on the “Next” button is redirected to the “Preview” page

- [ ] - All the filled information should be displayed on the “Preview” page

- [x] - Talent's information should be saved in the fields when switching between steps

- [x] - When required fields are empty or invalid data is entered (does not match validation requirements), fields are highlighted in red color and a validation message is displayed, a talent stays on this page and can’t move on next step

- [x] - When the talent moves on a new step the timeline should automatically progress

**Comment by ed9ward** [comment]
Tested
