### ISSUE TITLE
Add scrolling of the SignUp, SignIn forms

### ISSUE THREAD

**Issue by anogire** [BinaryStudioAcademy/bsa-2023-bsa-talents#275]
When the keyboard appears, the form is not fully scrolled and not all elements of the forms are visible.

**Comment by anna9314** [comment]
Tested
Works!

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/10447cdc-862c-491c-b3aa-b75a38665a82)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/d6184db8-42e6-438b-9684-e53e2ac48ebf)
