### ISSUE TITLE
[BUG] The layout of the page does not correspond to the approved design of "Sign Up" page

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#276]
**Description:**

The layout of the page does not correspond to the approved design of "Sign Up" page

**Environment:**
OS - Windows 
Browser - Google Chrome 
Version - 116.0.5845.141

**Steps to reproduce:**

1. Open the page http://localhost:3000/sign-up
3. Enter invalid password in the field “Password” (123@4)
4. Pay attention on  the field “Password”
5. Pay attention on the page layout

**Actual Result:**

1. The validation error message overlap radio button  with the label “I’m hiring” and a radio button with the label “I’m looking for a job”
2. The page contain text in the lower left corner
3. The page contain left sidebar 
4. The icon of the logo is located in the content area without the logo image. The logo image is located in the upper left corner
5. The page contain header 

**Expected Result:**

1. The validation error message  appears under the field “Password”, does not overlap radio button  with the label “I’m hiring” and a radio button with the label “I’m looking for a job”
2. The page must not contain text in the lower left corner
3. The page must not contain left sidebar
4. The logo is located in the content area
5. The page must not have header

**Visual Proof (screenshots, videos, text):**

**Severity:**

Major (S3)

![IMG_081](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/34d2b3c1-681d-4dff-b6d1-b6a820aa59e3)

**Comment by JosuerBague** [comment]
@Oleksandrra

For points 2 and 4 of Actual Result.

Do you want me to remove text and dummy logo?

**Comment by JosuerBague** [comment]
PR opened and linked.

**Comment by ed9ward** [comment]
Tested
