### ISSUE TITLE
Create Sign in form UI

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#29]
Create basic layout for sign in form (implement UI from screenshot).
There should be:

- [ ] Title
- [ ] Email form field
- [ ] Password form field
- [ ] Login button
- [ ] Create account button and text
- [ ] Forgot password button

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/103518438/81ddceed-2c44-4f62-8757-8d890e41c53b)

**Comment by illia-dobro** [comment]
Should I add a validation schema? (Or use the userSignUpValidationSchema)

We have a custom Link component, but I'm not able to add any styling to it. Should I leave it without any style?

**Comment by katerynakostikova** [comment]
Hello, if we have sign in validation schema in shared folder you can use it, if not, let's leave just UI for now.
You can add custom props for shared Link component if needed.
