### ISSUE TITLE
Create endpoint to get all badges and hard skills from db for select

### ISSUE THREAD

**Issue by MaksymGavatuk** [BinaryStudioAcademy/bsa-2023-bsa-talents#290]
Need to create GET endpoint for select options data (Screenshot 1, Screenshot 2)

- [x] create endpoint for hard skills
- [x] create endpoint for badges

(Screenshot 1)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/93519384/d69b61f8-2caa-4c39-ae2e-8ea656739cbf)

(Screenshot 2)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/93519384/c37bd37c-55a1-4f95-bf54-0dc648673c84)

**Comment by ed9ward** [comment]
Blocked without access to DB. Postponed as not a priority now.

**Comment by ed9ward** [comment]
Tested
