### ISSUE TITLE
Message You've been logged in appears without logging in [BUG]

### ISSUE THREAD

**Issue by ed9ward** [BinaryStudioAcademy/bsa-2023-bsa-talents#292]
**Description:**
Message You've been logged in appears even if you typed a wrong password and you have a validation message error.

**Environment:**
Win 11, Chrome 116

**Steps to reproduce:**
1. Fill in correct email and not the correct pass
2. Submit
3. Observe the popup and user status

**Actual Result:**
Message appears

**Expected Result:**
Message about log in doesn't appear when you're not logged in actually

**Visual Proof (screenshots, videos, text):**
![Image](https://user-images.githubusercontent.com/8355821/266266101-2f71f060-1390-4633-bf14-5d5f487b45f8.png)

**Severity:**
Minor (S4)

**Comment by JosuerBague** [comment]
Hello this will be removed in this PR: https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/276

That was a mock behaviour put in place for last demo.
