### ISSUE TITLE
Create employer page registration

### ISSUE THREAD

**Issue by lavandosya** [BinaryStudioAcademy/bsa-2023-bsa-talents#295]
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/116720360/89219127-1fd4-4410-880b-5985c67c4e99)

User story

As an Employer, I want to fill in the field about myself as a company representative and the company's info so that I can register and use the all functions of the platform

Acceptance criteria:

1. The content area of page must contain:

- the title “Create profile to find a perfect match to Your company”
- the subtitle “Fill in the fields below so that we can verify your company”
- the fields to type the user’s full name with title “Full name”
- the field to type user`s position in company with title “Your position”
- the fields to type the link to user’s LinkedIn profile with title “LinkedIn profile”
- the field to type user`s company name with title “Company name”
- the field to type link to user`s company web site with title “Company website”
- the dropdown component with title “Location”
- the field for typing the information about company with title “Briefly tell about your company and its values”
- the active button “Submit for verification”
- the active button “Preview” 

2. The sidebar of page  must contain:
- the icon for the user photo with an active link to upload the image over it
- the icon for the company logo with an active link to upload the image over it

3. The fields “Full name”,  “Your position”, “Company name”, “LinkedIn profile”, “Company website”, “Location” should required to the criteria that  are written in the [validation document](https://docs.google.com/spreadsheets/d/1OM1GunJPbMa6u0Dn4rm9Cgh32PBfMNOxv588UZYBM_4/edit?usp=sharing)
4. The images that can be uploaded should required to the criteria that are written in the [validation document](https://docs.google.com/spreadsheets/d/1OM1GunJPbMa6u0Dn4rm9Cgh32PBfMNOxv588UZYBM_4/edit?usp=sharing)
5.  The fields “Full name”,  “Your position”, “Company name”, “Company website”, “Location” must be marked as required, marked *
6. If a user leaves required fields empty, validation message with information that this field is required appears and empty fields light red color

**Comment by ed9ward** [comment]
Tested. Some minor bugs will be added separately.
