### ISSUE TITLE
[BUG] User is redirected to the onboarding steps when opening the localhost

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#305]
**Description:**
User is redirected to the onboarding steps when opening the localhost

**Environment:**
Windows 11 
Google Chrome 116.0

**Steps to reproduce:**

1. Open local host
2. Pay attention to the URL link and page

**Actual Result:**
User is redirected to the onboarding steps when opening the localhost

**Expected Result:**
User is redirected to the Sign in page when opening the localhost. User can't move to the onboarding without using a token

**Visual Proof (screenshots, videos, text):**
![Screenshot_5](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/aaca3dea-39b2-4caa-9260-f126b2942e7f)

**Severity:**
Major (S3)

**Comment by ed9ward** [comment]
Tested
