### ISSUE TITLE
[BUG] User is redirected to the onboarding steps after clicking on "Forgot Password?"

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#311]
**Description:**
User is redirected to the onboarding steps after clicking on "Forgot Password?" on the Sign in page

**Environment:**
Windows 11
Google Chrome 116.0

**Steps to reproduce:**
1.  Open the page http://localhost:3000/sign-in
2. Click on "Forgot Password?"

**Actual Result:**
User is redirected to the onboarding steps after clicking on "Forgot Password?" on the Sign in page

**Expected Result:**
User is redirected to the page to recover the password  after clicking on "Forgot Password?"

**Visual Proof (screenshots, videos, text):**
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/577913ac-2fe5-4570-8ea4-9ca4af914f23)

**Severity:**
Major (S3)

**Comment by JosuerBague** [comment]
We do not have the forgot password page yet so I routed this to home. Should we temporarily route this to page not found instead?

**Comment by JosuerBague** [comment]
PR #317 addresse the redirect to onboarding steps but this design is not an official design from Figma.

**Comment by ed9ward** [comment]
Tested
