### ISSUE TITLE
[BUG] Not depending on the placement of the slider name of the “Experience Level” is "Beginner" on the screen of step 01/05

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#313]
Description:
[Mobile]: Not depending on the placement of the slider name of the “Experience Level” is "Beginner" on the screen of step 01/05

Environment:
 OS - Android
 Version - 12 SP1A.210812.016

Severity Minor (S4)

Steps to reproduce:

1. Open the app
2. Sign Up with valid data, press “Sign Up”
3. After the redirecting move the slider of the “Experience Level”
4. Pay attention to the slider name

Actual Result:
Not depending on the placement of the slider name of the “Experience Level” is "Beginner" on the screen of step 01/05

Expected Result:
Year of Experience should be a range input with values from No(0 years) to 5+ years with a step of a 0,5 year
![slider](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/56a2f3c4-01a6-4d1d-9490-d017bde1ea31)

**Comment by anogire** [comment]
This has already been fixed [here](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/pull/304).

**Comment by nikita-remeslov** [comment]
No linked PR
