### ISSUE TITLE
[BUG] The layout of the Sign in page does not correspond to the approved design

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#318]
**Description:**
The layout of the Sign in page does not correspond to the approved design

**Environment:**
Android 13
Samsung Galaxy A52 (2340x1080)

**Steps to reproduce:**
1. Open BSA talent app
2. Pay attention to the page layout

**Actual Result:**
1. Email and password required fields don't have "*"
2.  Not Registered Yet and Create an account are out of bounds sign in screen

**Expected Result:**
1.  Email and password required fields have "*"
2. Not Registered Yet and Create an account correspond to the approved design
**Visual Proof (screenshots, videos, text):**
![Screenshot_11](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/c0a4884a-f67c-41f7-9f99-db8e1bf48f6f)

Sign in mockup:
![Screenshot_12](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/36930c88-ce64-4604-a45c-bb0b5cceb994)

**Severity:**
Major (S3)

**Comment by katerynakostikova** [comment]
I'd better remove the "Remember me" checkbox from the mobile app because it makes no sense. You can agree it with Product Owner

**Comment by anna9314** [comment]
Got it! Thanks to notice this!

**Comment by anna9314** [comment]
Tested


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/b330248a-8d0a-428d-88d8-1cf590b30c28)
