### ISSUE TITLE
Create Form Field component

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#32]
Create a shared component for a Form field. Let's modify existing Input component and Input will be only text input field without label & error.
Form field component should have:

- [ ] Label (if provided) 
- [ ] Required flag 
- [ ] Error (if provided)
- [ ] Children prop, so we can pass any input, checkbox, etc.

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/103518438/2c722db3-6608-4190-8b79-132ecec83e04)

**Comment by likeri29** [comment]
This component should be like a Wrapper? And be used in this way? `<FormField {props}>
<Input/>
</FormField>`

**Comment by katerynakostikova** [comment]
Yes, correct
