### ISSUE TITLE
No redirect to 404 page with wrong link in address bar

### ISSUE THREAD

**Issue by ed9ward** [BinaryStudioAcademy/bsa-2023-bsa-talents#323]
**Description:**
No redirect to the 404 page when putting a wrong link in the address bar from the onboarding steps.

**Steps to reproduce:**
1. Sign in to the app as a Talent
2. When you are on the onboarding steps page put any symbols at the end of the link in the address bar of your browser
3. Press enter

**Expected result:**
Redirected to 404 page if an address does not exist

**Actual result:**
First step Profile opened

**Visual proof:**
![Image](https://user-images.githubusercontent.com/8355821/266555167-2c00daf7-cba9-430f-bab3-ccf1ffadfb6d.gif)

**Severity:**
Minor

**Comment by JosuerBague** [comment]
Bug fixed in a separate ticket.
