### ISSUE TITLE
Connect badges & hard skills saving for user details

### ISSUE THREAD

**Issue by MaksymGavatuk** [BinaryStudioAcademy/bsa-2023-bsa-talents#326]
Save badges & hard skills from Onboarding (Screenshot 1 & Screenshot 2)

(Screenshot 1)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/93519384/a1ed1a14-8b24-461f-bc1f-71c26eec6ae8)

(Screenshot 2)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/93519384/723919a7-ee15-4c60-b4ef-ace1c9c30c31)

**Comment by ed9ward** [comment]
Tested
