### ISSUE TITLE
[BUG] The layout of the Step 01 page does not match the approved design

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#329]
**Description:**
The layout of the Step 01 page does not match the approved design

**Preconditions:**
The BSA talent app is open

**Environment:**
Android 13
Samsung Galaxy A52 (2340x1080)

**Steps to reproduce:**
1. Enter valid email and password
2. Click on Sign up
3. Pay attention to the Step 01 layout

**Actual Result:**
1. Fields have different colors of placeholders
2. Salary expectations, job title, current location fields are not highlighted in red where empty
3. Salary expectations field is not required 
4. Wrong name and slider of Experience field. Experience slider shows "Beginner"
5. Salary expectations field has a default "0" number

**Expected Result:**
1. Placeholder for all fields matches the design
2. Salary expectations, job title, current location fields are highlighted in red where empty
3. Salary expectations field is displayed validation message and  highlighted in red where empty
3. Experience slider has the name "Experience" and shows years of experience (1, 1.5, 2.....).
4. Salary expectations field has a placeholder like on the design

**Visual Proof (screenshots, videos, text):**
![step 01](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/749611c4-7a73-4cdc-97d7-d21d82eb5ec2)
![step 1](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/1287c370-1700-48af-ba8b-3ae2a82057b6)
![step_01](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/0454a902-9971-40dc-b2bc-2f9254aad108)

**Severity:**
Major (S3)

**Comment by anogire** [comment]
**3. Salary expectations field is not required**
This is a required field by design, or am I wrong?

**Comment by anna9314** [comment]
Yes, this is a required field. But these fields are not highlighted in red where empty - Salary expectations, job title, current location.  These fields should be highlighted in red and have a validation message where empty

**Comment by anna9314** [comment]
I see the salary expectations field has validation when removing 0, but this field should have a placeholder, not default 0

**Comment by ed9ward** [comment]
Tested


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/1845d54d-9441-4552-99e0-d2cafc8c1c66)

**Comment by anna9314** [comment]
@anogire Have you changed the name of the experience field because we still have this bug?
 [[BUG] Wrong name of the "Experience" field on Step 01#395](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/395)
