### ISSUE TITLE
[BUG] The "Step" in the right upper corner is moved to another line 

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#330]
**Description:**
 The "Step" in the right upper corner is moved to another line  when the screen resolution is 2340x1080

**Preconditions:**
The BSA talent app is open

**Environment:**
Android 13
Samsung Galaxy A52 (2340x1080)

**Steps to reproduce:**
1. Choose 2340x1080 resolution 
2. Enter a valid email and password
3. Click on Sign up
4. Pay attention to the Step in the right upper corner 

**Actual Result:**
The "Step" in the right upper corner is moved to another line when the screen resolution is 2340x1080

**Expected Result:**
The "Step" in the right upper corner is displayed fully

**Visual Proof (screenshots, videos, text):**
![Screenshot_2](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/c977855b-dcfe-4eee-b90f-fde90ddf1bcb)

**Severity:**
Major (S3)

**Comment by nikita-remeslov** [comment]
Link PR

**Comment by anna9314** [comment]
Tested
https://prnt.sc/D4ldTZ0w4w7D
