### ISSUE TITLE
Adapt the sidebar for mobile layout for the whole project

### ISSUE THREAD

**Issue by Simpsonkk** [BinaryStudioAcademy/bsa-2023-bsa-talents#332]
The sidebar should hide on mobile and add a hamburger menu on the header

**Comment by Oleksandrra** [comment]
Tested

https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/91033a40-0a4d-4fbd-aa7e-bb13eba25c2c
