### ISSUE TITLE
Forgot password functionality

### ISSUE THREAD

**Issue by MaksymGavatuk** [BinaryStudioAcademy/bsa-2023-bsa-talents#333]
Need to implement forgot password flow (Screenshot 1)
- [x] describe the flow
- [x] create email package for example using SendGrid
- [x] made changes in db and add methods to services
- [x] create resetPassword endpoin

Little hint: (https://blog.logrocket.com/implementing-secure-password-reset-node-js/)

Screenshot 1
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/93519384/e548e740-fea9-4e5b-9afd-1e2c8c225a0e)

**Comment by ed9ward** [comment]
Need to add redirection on AWS when clicking on reset password link from email.
