### ISSUE TITLE
Connect file saving to onboarding proccess

### ISSUE THREAD

**Issue by MaksymGavatuk** [BinaryStudioAcademy/bsa-2023-bsa-talents#335]
We have file uploading in our onboarding proccess (Screenshot 1). And we need connect file saving with backend.
- [ ] use upload endpoint to upload file to AWS from this PR (https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/pull/273)
- [ ] get fileId from response
- [ ] provide these ids to userDetails request for PATCH endpoint

Screenshot 1
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/93519384/d95eb15b-337d-436f-a78a-e2d5de9039af)

**Comment by ed9ward** [comment]
Tested
