### ISSUE TITLE
Create basic endpoint to get user details by id

### ISSUE THREAD

**Issue by MaksymGavatuk** [BinaryStudioAcademy/bsa-2023-bsa-talents#337]
Create basic endpoint for this page (Screenshot 1)
- [x] create query in repository 
- [x] create method in service
- [x] create controller for this route

Screenshot 1
![Image](https://user-images.githubusercontent.com/93519384/266701084-088211e7-35a3-49c0-8636-2f209f906f72.png)

**Comment by nikita-remeslov** [comment]
@nika-sirak Link PR

**Comment by ed9ward** [comment]
Tested
