### ISSUE TITLE
Add logout button to Drawer navigation

### ISSUE THREAD

**Issue by anogire** [BinaryStudioAcademy/bsa-2023-bsa-talents#348]
The changes have been agreed with the PO.
![Image](https://user-images.githubusercontent.com/70234990/266965744-1609e681-2a0c-4811-bb15-85e5644d5d71.png)

**Comment by Oleksandrra** [comment]
Tested

https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/45530e57-7891-4de2-90ed-6f2297d67146
