### ISSUE TITLE
Use our logo for Loader

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2023-bsa-talents#355]
**Acceptance criteria:**
- When the user accesses the website, the BSA talent logo as a loader should be displayed to indicate that the website is in the process of loading.
- When the loader is active, the BSA talent logo must be clearly visible to the user.
- The logo loader should remain visible for the entire duration of the loader's operation. It should not disappear.
- The logo loader should be positioned in the middle of the page
- The logo loader must have sufficient contrast with the loader's background to ensure it is clearly distinguishable, readable, and matches with design

**Comment by ed9ward** [comment]
Tested
