### ISSUE TITLE
[BUG] Step 4 doesn't correspond the design

### ISSUE THREAD

**Issue by ed9ward** [BinaryStudioAcademy/bsa-2023-bsa-talents#356]
**Description:**
The layout of the Step 4 page does not correspond to the approved design

**Environment:**
Win 11, Chrome 116

**Steps to reproduce:**
1. Sign in to the app as a Talent
2. Go to Step 4
3. Fill in all fields with valid data as on the screenshot
4. Pick an image >5mb in the photo selector to error hint appear
5. Pick an image <5mb

**Actual Result:**
1. Choose a photo button placed under the photo preview
2. There is a space between field names and the "*" symbol
3. Full name placeholder is Name
4. LinkedIn "www" placeholder without a dot at the end.
5. LinkedIn hint isn't informative for a user
6. CV "+" symbol is not aligned with Choose file text
7. Text block under CV has bigger margin than on the design
8. CV and Contacts step name has small letter in "contacts"
9. Hint about a big photo or CV file doesn't disappear after user uploads a valid file
10. Phone number validation accepts only Ukrainian +380 numbers

**Expected Result:**
1. Choose a photo button placed on the right side of the photo preview
2. There shouldn't be a space between fields name and the "*" symbol as on the design
3. Full name placeholder is Name Name
4. LinkedIn "www." placeholder with a dot at the end.
5. Add more info on how we expect to validate this field in hint. At least mask.
6. CV "+" symbol is aligned with Choose file text
7. Text block under CV has the same margin as on the design
8. CV and Contacts step name has a capital letter in "Contacts"
9. Hint about a big photo or CV file disappears after user uploads a valid file
10. Phone number validation accepts any country codes and numbers

**Visual Proof (screenshots, videos, text):**
![Image](https://user-images.githubusercontent.com/8355821/266629548-3835b935-fa90-481a-a146-13658d47e22e.png)

Typo Contacts
![Image](https://user-images.githubusercontent.com/8355821/266630974-370fd86d-1819-44ef-b5da-1a8e8f9e566d.png)
![Image](https://user-images.githubusercontent.com/8355821/266630979-4729ec40-3ae4-4c75-98d3-f6fe6a9085c6.png)

Number validation
![Image](https://user-images.githubusercontent.com/8355821/266574005-dd9319db-a6d7-43ab-83e2-a91da9538863.png)

The message doesn't disappear
![Image](https://user-images.githubusercontent.com/8355821/266376051-dcc0d827-c886-49ec-8ea1-1e07ebe42ae2.png)
![Image](https://user-images.githubusercontent.com/8355821/266573521-a63707cb-612e-4a47-8dd6-9e0f4ae3ac36.png)

**Severity:**
Minor

**Comment by nika-sirak** [comment]
- [x] Choose a photo button placed on the right side of the photo preview

- [x] There shouldn't be a space between fields name and the "*" symbol as on the design

- [x] Full name placeholder is Name Name

- [x] LinkedIn "www." placeholder with a dot at the end.

- [x] Add more info on how we expect to validate this field in hint. At least mask.

- [x] CV "+" symbol is aligned with Choose file text

- [x] Text block under CV has the same margin as on the design

- [x] CV and Contacts step name has a capital letter in "Contacts"

- [x] Hint about a big photo or CV file disappears after user uploads a valid file

- [x] Phone number validation accepts any country codes and numbers

**Comment by ed9ward** [comment]
Tested
