### ISSUE TITLE
[BUG] Password validation message typo on Sign up/Sign in pages

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#357]
**Description:**
 Password validation message typo on Sign up/Sign in pages

**Environment:**
Android 13
Samsung Galaxy A52 (2340x1080)

**Steps to reproduce:**
1. Open BSA talent app
2. Enter a password less than 8 char
3. Pay attention to the validation message

**Actual Result:**
The validation message is displayed with a small letter and with quotes.

**Expected Result:**
The validation message is displayed same style throughout the app with a capital letter and no quotes.

**Visual Proof (screenshots, videos, text):**
First case: we have a password with a small letter and quotes.
![Screenshot_2](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/51dc35d1-38e5-429b-8d64-216f1d76f9bc)

Second: we have it Password with a capital.
![Screenshot_1](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/1747b3e8-459d-4195-9b13-a78891d622f7)

**Severity:**
Minor (S4)

**Comment by illia-dobro** [comment]
Check please again, because I have this, and the code looks okay.

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/112649713/0ad3ac6c-e65f-44c3-bc1e-2a4e9f69ecc7)

**Comment by anna9314** [comment]
Yes, now everything is ok!

**Comment by mskmee** [comment]
As for me it's bad to user expirence, when we shoing password should be 8 chars long, user enterin 12345678 and got this error. We should show pattern or remove it at all....

**Comment by anna9314** [comment]
Tested
