### ISSUE TITLE
[BUG] The "I'm hiring/ I'm looking for the job" radio buttons go outside of the Sign up form

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#359]
**Description:**
The "I'm hiring/ I'm looking for the job" radio buttons go outside of the Sign up form when the resolution is 1280x720

**Environment:**
Android 10
SamsungGalaxy J7 Neo (1280x720)

**Steps to reproduce:**
1. Open BSA talent app
2. Click on "Create an account"
3. Pay attention to the "I'm hiring/ I'm looking for the job" radio buttons

**Actual Result:**
The "I'm hiring/ I'm looking for the job" radio buttons go outside of the Sign up form the resolution is 1280x720

**Expected Result:**
The "I'm hiring/ I'm looking for the job" radio buttons are fully displayed on the Sign up form

**Visual Proof (screenshots, videos, text):**
![radio_button](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/3bfe56c5-3527-4eea-bef5-5954fe0ce8f2)

**Severity:**
Minor (S4)

**Comment by Oleksandrra** [comment]
https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/159 added comment about dropdown

**Comment by illia-dobro** [comment]
Is this bug happening on a real phone? The issue is not occurring on the emulator with a resolution of 720x1280.

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/112649713/17d41eaa-5873-4f59-94a0-b0404d1ed19d)

**Comment by Oleksandrra** [comment]
@illia-dobro yes, we are testing mobile app on real phone

**Comment by anna9314** [comment]
Tested


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/d549ee35-a593-4d62-bc8f-fb55a4c13437)
