### ISSUE TITLE
[BUG] Selector list should appear above screen content

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#365]
Description:
When user click on selector component, screen content under it moved with the list

Environment:
OS - Android

Steps to reproduce:

1. Open the app
2. Go to onboarding step 3
3. Tap on selector component

Actual Result:
Selector list moved all screen content under it 

Expected Result:
Selector list should appear above screen content

https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/103518438/77ea2f06-9127-4151-bac9-fc25edb451cb

**Comment by ed9ward** [comment]
Tested
