### ISSUE TITLE
Add Step 5 (Preview screen) to talent onboarding

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#368]
Design link: [https://www.figma.com/file/Yd7USgP7PLvA0W794jHXWu/BSA_recruting?type=design&node-id=7318-9656&mode=design&t=Tm68KisNxezn0fDM-0](https://www.figma.com/file/Yd7USgP7PLvA0W794jHXWu/BSA_recruting?type=design&node-id=7318-9656&mode=design&t=Tm68KisNxezn0fDM-0)

User story:

As a Talent, I want to be able to see my profile, so that I can read/review all information that I filled in the previous steps

Acceptance criteria:

1. The step number “STEP 05/05” is placed in the upper right corner on the same line with the title of the page “Preview”
2. The content area of the page must contain:
- the information about the job title that the user chose
- the information about the size of salary expectation that the user chose
- the information about the years of experience that the user chose
- the information about the English level that the user chose
- the information about the employment type that the user chose
- the information about the vacancies that the user does not consider
- the information about the Talent's date account publishing
- the user’s cover letter
- active tabs: Scores & skills, Feedbacks, Project
- the active button “Save without publishing” 
- the active button “Publish now”

3. The tab “Scores & skills” must contain:
- the BSA badges with labels and scores
- the information about the skills that the user chose
- 
4. The tab “Feedbacks” must contain HR comments about the Talent's skills:

- information about personality type, the selected components are displayed as tags
- HR badges, the selected components are displayed as tags

5. The tab “Project” must contain information about Talent’s project that includes data about the duration of the project, composition and specialization of the team, the scope of the project, project preview

6. The layout must match the design posted on Figma (specified above)

**Comment by Oleksandrra** [comment]
tested

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/74f57a6a-9df1-4aa9-aa62-fc34e4ecd9e5)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/17ea1708-bc67-42e6-b2cb-a311577bfd75)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/351cbdf9-8af8-4463-bc24-d1d2349f283b)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/ab7e9628-fa7c-48c1-88e9-a80edc9b9146)
