### ISSUE TITLE
Add onboarding screen for employer

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#369]
Note: since we have only wireframe pay more attention to logic, not to design 

Miro link: [https://miro.com/app/board/uXjVMwsyMQ4=/?share_link_id=911133682634]( https://miro.com/app/board/uXjVMwsyMQ4=/?share_link_id=911133682634)

![Image](https://user-images.githubusercontent.com/103518438/267031297-4f7451a6-f565-45c9-a371-b317781372bb.png)

User story

As an Employer, I want to fill in the field about myself as a company representative and the company's info so that I can register and use the all functions of the platform

Acceptance criteria:

1. The content area of page must contain:
- the title “Create profile to find a perfect match to Your company”
- the icon for the user photo with an active link “Choose photo” to upload the image over it
- the icon for the company logo with an active link “Choose logo” to upload the image over it
- the fields to type the user’s full name with title “Full name”
- the field to type user`s position in company with title “Your position”
- the fields to type the link to user’s LinkedIn profile with title “LinkedIn profile”
- the field to type user`s company name with title “Company name”
- the field to type link to user`s company web site with title “Company website”
- the dropdown component with title “Location”
- the field for typing the information about company with title “Briefly tell about your company and its values”
- the active button “Submit for verification”

2. The information entered in the  fields “Full name”,  “Your position”, “Company name”, “LinkedIn profile”, “Company website”, “Location” should be required to the criteria that  are written in the [validation document](https://docs.google.com/spreadsheets/d/1OM1GunJPbMa6u0Dn4rm9Cgh32PBfMNOxv588UZYBM_4/edit?usp=sharing)
3. The images that can be uploaded should be required to the criteria that are written in the [validation document](https://docs.google.com/spreadsheets/d/1OM1GunJPbMa6u0Dn4rm9Cgh32PBfMNOxv588UZYBM_4/edit?usp=sharing)
4. After clicking on the “Choose photo” link should be 2 options: launch the gallery or take a picture from the camera
5. After clicking on the “Choose logo” link launch the gallery
6. The fields “Full name”, “Your position”, “Company name”, “Company website”, “Location” must be marked as required, marked *
7. If a user leaves required fields empty, a validation message with information that this field is required appears and empty fields light red color
8. After the pressing button “Submit for verification” information is sent for approval to Admin

**Comment by katerynakostikova** [comment]
Build in 20 minutes

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695115227854739

**Comment by ed9ward** [comment]
Tested
