### ISSUE TITLE
Сreate seeds to create all base badges and hard skills

### ISSUE THREAD

**Issue by Simpsonkk** [BinaryStudioAcademy/bsa-2023-bsa-talents#370]
create a list of hard skills and make a seed
 
**Acceptance criteria:**

Should be the following list of badges:

By personality: Doer / Connector / Thinker
By soft skills: Communicative, Collaboration, Problem-solving, Leadership, Creative, Proactive
By BSA score: Project average score, Lectures average score, Communication score, Working with team score, Level of English, Punctuality

Should be the following list of skills:

JavaScript
Python
Java
C++
Ruby
PHP
Swift
Go
Kotlin
HTML/CSS
React.js
Angular
Node.js
SQL Database Management
NoSQL Database Management
Database Design
Cloud Computing
DevOps 
Cybersecurity
Network Administration
Big Data 
Machine Learning
Artificial Intelligence
Web Development
Mobile App Development
API Development
Software Testing
Project Management
UI/UX Design
Front-end Development
Back-end Development
Full-stack Development
Blockchain Development
Data Science
IT Support
Scripting
IT Security Compliance
Automation
Data Analytics
Cloud Security
RESTful APIs
System Administration
Continuous Integration/Continuous Deployment (CI/CD)
Marketing 
Project Management
Product Management
SEO
AWS
Azure
GCP
Slack
Miro
Git
Figma
Microsoft Office Suite
G Suite
Dropbox
Trello
Asana
JIRA
Confluence
Basecamp
Git

**Comment by Monyster** [comment]
Hard skills are good, but what about badges, they have "type" and "max_score" fields that are not described here?
```
ID: 'id',
TYPE: 'type',
NAME: 'name',
MAX_SCORE: 'max_score'
```

**Comment by anna9314** [comment]
I will clarify this with the PO tomorrow

**Comment by anna9314** [comment]
Tested
