### ISSUE TITLE
[BUG] Swagger does not work on staging

### ISSUE THREAD

**Issue by MaksymGavatuk** [BinaryStudioAcademy/bsa-2023-bsa-talents#375]
**Description:**
Swagger doesn't work on staging

**Preconditions:**
-

**Environment:**
Development env on AWS

**Steps to reproduce:**

1. Go to http://bsa-talents.us-east-1.elasticbeanstalk.com/api/v1/documentation/static/index.html
2. There are no routes in swagger docs

**Actual Result:**

![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/93519384/98f0e5b3-2ffd-4920-97b6-9918697ca856)

**Expected Result:**

![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/93519384/1b76a850-aacd-4e3d-863b-56c3309b5bf0)

**Visual Proof (screenshots, videos, text):**

![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/93519384/98f0e5b3-2ffd-4920-97b6-9918697ca856)

**Severity:**
Major (S3)

**Comment by nikita-remeslov** [comment]
@MaksymGavatuk link PR please

**Comment by ed9ward** [comment]
Working
