### ISSUE TITLE
Replace mocked data (badges, hard skills) in oboarding screens with data fetched from backend

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#381]
We need to replace mocked data for badges and hard skills 

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/103518438/dc76783a-88b3-431f-aeeb-23c41d43b808)

**Comment by ed9ward** [comment]
Tested
