### ISSUE TITLE
[BUG] The chosen country does not display in the field "Current location"

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#384]
**Description:**
[Mobile]: The chosen country does not display in the field "Current location"

**Preconditions:**

**Environment:**
OS - Android 12
App build 13/09/2023 3:40PM

**Steps to reproduce:**

1. Open the app
2. Sign Up with valid data, press “Sign Up”
3. Fill in the required fields on the page “Step 01/05”
4. Choose country in the field "Current location"
5. Pay attention that chosen country does not display in the field "Current location"
6. Press button “Next”
7. Pay attention that validation error about empty field "Current location" does not appears, user is redirected to the next step

**Actual Result:**
The chosen country does not displayed in the field "Current location". The validation error about empty field "Current location" does not appears, user is redirected to the next step

**Expected Result:**
The chosen country displayed in the field "Current location"

**Visual Proof (screenshots, videos, text):**
https://user-images.githubusercontent.com/8355821/267261072-466b16ad-d80f-4e20-9b8a-5cb2b026ccbb.mp4
https://drive.google.com/file/d/11rvz9DF9wX5Y-QuWzNB2VN3I-yXTlWtd/view?usp=drivesdk

**Severity:**
Medium

**Comment by anogire** [comment]
It also in this [PR](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/pull/366)

**Comment by ed9ward** [comment]
Still exists in my env, latest build from 09AM 12.09

https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/466b16ad-d80f-4e20-9b8a-5cb2b026ccbb

**Comment by ed9ward** [comment]
Other device:
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/78fb0098-dff4-4f43-8a53-0e56253e978a)

**Comment by ed9ward** [comment]
Returned to In progress

**Comment by anna9314** [comment]
Tested
https://prnt.sc/nn8Oo8hDOjCz
