### ISSUE TITLE
[BUG] Fix input placeholder color

### ISSUE THREAD

**Issue by ed9ward** [BinaryStudioAcademy/bsa-2023-bsa-talents#386]
**Description:**
The color of the text input doesn't match the design and other placeholder's color.

**Environment:**
Android 12, Realme 8

**Steps to reproduce:**
1. Compare the placeholder's input color with the design

**Actual Result:**
Colors of placeholders should be the same in all inputs

**Expected Result:**
The color of text input's placeholder is different. Text input has a little bit lighter color.

**Visual Proof (screenshots, videos, text):**
![Image](https://user-images.githubusercontent.com/8355821/267263994-f9e80b31-2ad7-4dda-a768-aabd0b87e755.png)

**Severity:**
Trivial

**Comment by ptarho** [comment]
I think this is already fixed on linked PR

**Comment by ed9ward** [comment]
Tested
