### ISSUE TITLE
[BUG] Step 4 mobile bugs

### ISSUE THREAD

**Issue by ed9ward** [BinaryStudioAcademy/bsa-2023-bsa-talents#392]
**Description:**
Step 4 doesn't correspond to the design

**Environment:**
Android 12

**Steps to reproduce:**
1. Go to Step 4
2. Select Phone number field
3. Click Next button

**Actual Result:**
3. Linked in has unclear hint
4. Phone number validation accepts only Ukrainian +380 numbers

**Expected Result:**
3. LinkedIn has hint as on web "Link format must be https://www.linkedin.com/in/"
4. Phone number validation accepts any country codes and numbers

**Visual Proof (screenshots, videos, text):**
![Image](https://user-images.githubusercontent.com/8355821/267327280-7169fbc3-a0d5-439b-998b-11b7e82c6e14.jpg)
![Image](https://user-images.githubusercontent.com/8355821/267327296-d4df8b6c-e720-428b-8724-b0992727d5b2.jpg)

**Severity:**
Major

**Comment by illia-dobro** [comment]
Please test. I think we do not have these issues anymore.

**Comment by ed9ward** [comment]
This two bugs are still valid

**Comment by illia-dobro** [comment]
![plus](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/112649713/beb44b3a-ffc2-4ab1-9214-a360bc6ec3b0)

![num](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/112649713/8959978f-1faf-4780-80e0-125c831907d6)

**Comment by ed9ward** [comment]
You need to add a hint for LinkedIn: Link format must be https://www.linkedin.com/in/
Try to type Polish phone +48732031077, it won't work, it accepts only Ukrainian numbers now. We should fix it.

**Comment by katerynakostikova** [comment]
@ed9ward Our product owner asked us to use links without https: and www. to match design

**Comment by ed9ward** [comment]
Ok, then just fix issue with foreign phone numbers and will close this

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695886214948429

**Comment by ed9ward** [comment]
Tested
