### ISSUE TITLE
[BUG] Wrong name of the "Experience" field on Step 01

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#395]
**Description:**
Wrong name of the "Experience" field on Step 01

**Preconditions:**
The BSA talent app is open

**Environment:**
Android 13
Samsung Galaxy A52 (2340x1080)

**Steps to reproduce:**
1. Enter a valid email and password
2. Click on Sign up
3. Pay attention to the name of the "Experience" field

**Actual Result:**
Field has the name "Experience Level"
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/5cdc031a-0036-4ab4-90ca-9caa4d9243d8)

**Expected Result:**
Field has the name "Experience"
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/b54d681c-4f50-4bc0-85f9-32cc7a2bb3ea)

**Severity:**
Minor (S4)

**Comment by anogire** [comment]
I'll fix

**Comment by anna9314** [comment]
Tested
https://prnt.sc/wI8sAyj52fzV
