### ISSUE TITLE
Add transition to elements for Onboarding Flow

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#397]
When the user hovers over the elements there should be a visual effect
Also, it is necessary to add a transition for states updates
https://developer.mozilla.org/en-US/docs/Web/CSS/transition

**Comment by Monyster** [comment]
What elements? Inputs, buttons?


Transition for blue line?
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/42421305/d77da05d-4288-430c-95a0-6f218ae92418)

**Comment by anna9314** [comment]
Tested
