### ISSUE TITLE
Change the requirements for the mandatory field "I do not consider" Step 3

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#407]
The field "I do not consider" is not mandatory, not marked

**Comment by ptarho** [comment]
Can you provide more information about this issue? Because currently it`s mandatory, marked as required and validated
![Screenshot_7](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/67747035/01835491-dc05-47c3-b791-8cea71748b6c)

**Comment by Oleksandrra** [comment]
@ptarho
The design doesn't correspond to the updated requirements:
If user leaves this field empty, the field does not light red 
Even if user doesn't fill in this field, can move to the next step

**Comment by anna9314** [comment]
Tested
https://prnt.sc/xnkifGQ2BVwK
