### ISSUE TITLE
Change the requirements for the mandatory field "I do not consider" Step 3

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#408]
The field "I do not consider" is not mandatory, not marked *

**Comment by ed9ward** [comment]
Create the same for web
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/de562a23-e0f9-4d1e-be7b-821abced0621)

**Comment by anna9314** [comment]
Tested
https://prnt.sc/FUANEuU4B_B3
