### ISSUE TITLE
[BUG] Side form with steps shows wrong current step

### ISSUE THREAD

**Issue by ed9ward** [BinaryStudioAcademy/bsa-2023-bsa-talents#416]
**Description:**
Side form with steps shows almost always Step 4 regardless of active current step

**Environment:**
Android 12

**Steps to reproduce:**
1. Sign in to the app as Talent
2. Go to the third step
3. Open burger menu with steps

**Actual Result:**
Step 4 is shown as active

**Expected Result:**
Current step should be shown as active

**Visual Proof (screenshots, videos, text):**
https://user-images.githubusercontent.com/8355821/267707415-0da3cb60-5358-447b-8e85-d810d5669d2c.mp4

**Severity:**
Minor

**Comment by illia-dobro** [comment]
This behavior is now different after some PRs were merged.

**Comment by ed9ward** [comment]
Tested
