### ISSUE TITLE
[BUG] Error message when user tries to Sign up

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#418]
**Description:**
Error message is displayed when user tries to Sign up

**Preconditions:**
Site is open http://bsa-talents.us-east-1.elasticbeanstalk.com/sign-up

**Environment:**
OS Windows 11
Google Chrome 116.0

**Steps to reproduce:**
1. Enter a valid email and password
2. Pat attention to response

**Actual Result:**
User is relocated to the onboarding flow

**Expected Result:**
Error message is displayed when user tries to Sign up

**Visual Proof (screenshots, videos, text):**
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/d4809160-1f75-4def-be72-24437a2efd7c)
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/0ac3bbb0-f86d-4575-83cd-33f1940f269c)

**Severity:**
Critical (S2)

**Comment by ed9ward** [comment]
Same with Sign In
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/56564b85-ed29-47b5-926c-b4105b7ce4fe)

**Comment by JosuerBague** [comment]
This is strange, it is an inconsistent bug. @anna9314 @ed9ward .

I tried signing up locally using this:
josh@gmail.com
<password> (never changed)

I had 2 instances where I was told I had incorrect email.
While in staging i registered with no problem.

**Comment by anna9314** [comment]
@JosuerBague Now, it works. Problem was with AWS
