### ISSUE TITLE
[BUG] The button “Back” doesn’t redirect to the previous page on the page “Step 03/05”

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#420]
**Description:**
[Mobile]: The button “Back” doesn’t redirect to the previous page on the page “Step 03/05”

**Preconditions:**
The user is on the page “Step 03/05”

**Environment:**
OS - Android
Version - 12 SP1A.210812.016

**Severity**
Critical (S2)

**Steps to reproduce:**

1. Press “Back” on the page “Step 03/05”
2. Pay attention that the user stays on the page “Step 03/05”
3. Press the phone navigation button “Back”
4. Pay attention that the user is redirected to the page “Step 01/05”

**Actual Result:**
The button “Back” doesn’t redirect to the previous page on the page “Step 03/05”. After using the phone navigation button “Back” the user is redirected to the page “Step 01/05” (the same situation on page “Step 04/05”.

**Expected Result:**
The button “Back” on the page “Step 03/05” redirects to the previous page “Step 02/05”

**Visual Proof (screenshots, videos, text):**
https://drive.google.com/file/d/12TQDhmj7xpraQaYStZRMk0CSJ7Mewi1i/view?usp=sharing

**Comment by anna9314** [comment]
tested
