### ISSUE TITLE
Add Dropdown component for sorting the search result

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#423]
Acceptance criteria:

1. Should apply requirements for common dropdown component
2. Should have options
- sort by salary in ascending order 
- sort by salary in descending order 
- sort by experience in ascending order 
- sort by experience in descending order 
- sort by newest 
- sort by oldest 

![sort](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/873a3b75-0635-445a-8258-efe681935777)

**Comment by ed9ward** [comment]
Tested
