### ISSUE TITLE
[BUG] Progress bar is not displayed in blue color when step is completed

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#428]
**Description:**
Progress bar is not displayed in blue color when the step is completed

**Preconditions:**
The BSA talent app is open

**Environment:**
Android 13
Samsung Galaxy A52 (2340x1080)

**Steps to reproduce:**
1. Enter a valid email and password
2. Click on Sign up
3. Fill in steps
3. Pay attention to the progress bar

**Actual Result:**
Progress line has 2 states: disabled and active
Progress bar is not displayed in blue color when step is completed

**Expected Result:**
Progress line has 3 states: disabled (grey), active(white), and completed(blue)

**Visual Proof (screenshots, videos, text):**
https://drive.google.com/file/d/1f4bxgl6l1_Xgeb3aobrj5PAJ55VNdCoL/view?usp=drive_link

**Severity:**
Major (S3)

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695042744684699

**Comment by ed9ward** [comment]
Now V mark is shown, but also a thin line behind it. Need to remove it.

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/d413d5d2-219d-4f6a-a595-3dcd304442e5)

**Comment by mskmee** [comment]
will fix it in https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/pull/505

**Comment by katerynakostikova** [comment]
Build in 20 minutes

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695115227854739

**Comment by ed9ward** [comment]
Tested
