### ISSUE TITLE
[BUG] Wrong color of placeholder for the "Job title" field

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#430]
**Description:**
Wrong color of placeholder for the "Job title" field on Step 01

**Preconditions:**
The BSA talent app is open

**Environment:**
Android 13
Samsung Galaxy A52 (2340x1080)

**Steps to reproduce:**
1. Enter a valid email and password
2. Click on Sign up
3. Pay attention to the "Job title" field

**Actual Result:**
The color of the placeholder for the "Job title" field different from other fields

**Expected Result:**
The "Job title" field has a placeholder like other fields (like the "Current location" field)

**Visual Proof (screenshots, videos, text):**
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/22903a96-7dd9-43bb-a4a5-b6e4797206e5)

**Severity:**
Low

**Comment by anna9314** [comment]
@anogire Have you fixed this? I still have a different font-weight


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/1beab9fa-8f10-4240-b15d-1a976ddd43a4)

**Comment by anogire** [comment]
For value should be black color. Only when there is no value - we have placeholder with light-blue color

**Comment by anna9314** [comment]
tested

**Comment by ed9ward** [comment]
Placeholder text style still differs:

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/6241e3a8-d803-4941-abcc-39258201963f)
