### ISSUE TITLE
Connect get user data API to mobile and remove related TODOs

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#433]
[http://bsa-talents.us-east-1.elasticbeanstalk.com/api/v1/documentation/static/index.html#/User%20Details/get_user_details__userId_](http://bsa-talents.us-east-1.elasticbeanstalk.com/api/v1/documentation/static/index.html#/User%20Details/get_user_details__userId_)

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695286800288659

**Comment by ed9ward** [comment]
Tested
