### ISSUE TITLE
Create Chat user details screen

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#435]
**User story:**
As a talent, I want to be able to see a block with information about potential employers on the chat screen, so that I can find out about a company before I accept the contact

**Acceptance criteria:**

- Talent should be able to see a logo of a company, the full name of the employer, the job position of the employer
- Talent should be able to see a brief description of a company
- There should be a company link that talent can go to the company's website by clicking on it
- There should be the “Share your contact and CV” button
- Under “Share your contact and CV” button should be a block “Has the employer already hired you?” - title, “Yes” and “No” radio buttons and the “Submit” button below (like on the Candidate's page)
- When a talent taps on the “Submit” button, the confirmation window should appear
- The "Are you sure you want to confirm this action?" confirmation window should have "Yes" and "Cancel" buttons

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/103518438/8f7c96e3-a109-4c12-8390-cf5990cb48ef)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/22e28792-f568-4444-bcba-86e83c8d7e73)

**Comment by katerynakostikova** [comment]
Build in 20 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695286800288659

**Comment by ed9ward** [comment]
Tested
