### ISSUE TITLE
Update talent-onboarding preview-step data to real

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#437]
**Acceptance criteria:**

- "Profile name", "Salary expectations", "Current location", "Experience", "Level of English", "Employment type", "I don't consider" should be displayed on the Preview page after the talent finishes onboarding
- Selected/chosen by default badges should be displayed on the Preview page after the talent finishes onboarding
- "Hard Skills" and "Preferred Language" should be displayed on the Preview page after the talent finishes onboarding
- "Briefly tell employers about your experience" should be displayed on the Preview page after the talent finishes onboarding in the Cover letter section
- When clicking on the "Repository link" button user should be redirected to the repo (if talent added a project link)

**Comment by ed9ward** [comment]
Tested
