### ISSUE TITLE
[BUG] Wrong color of placeholder for " Preferred language communication" field

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#443]
**Description:**
Wrong color of placeholder for " Preferred language communication" field on step 03

**Preconditions:**
The BSA talent app is open

**Environment:**
Android 13  
Samsung Galaxy A52 (2340x1080)

**Steps to reproduce:**
1. Enter a valid email and password
2. Click on Sign up
3. Go to step 3
4. Pay attention to the color of the placeholder for the " Preferred language communication" field

**Actual Result:**

**Expected Result:**
The " Preferred language communication" field has the same color of the placeholder as the "Level of English" field

**Visual Proof (screenshots, videos, text):**
![Screenshot_4](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/d1d4815b-9d82-4d05-82df-3b24d786e242)

**Severity:**
Minor (S4)

**Comment by ed9ward** [comment]
Tested
