### ISSUE TITLE
[BUG] The field "I do not consider" mark *, as mandatory

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#446]
**Description:**
Not required field mark *, as mandatory

**Preconditions:**
The user is on the page  "Step 03/05"

**Environment:**
OS Windows
Browser Firefox
Version 117.0.1

**Steps to reproduce:**

1. On page  "Step 03/05" pay attention to the title "I do not consider"

**Actual Result:**
The field "I do not consider" mark *, as mandatory. This field is optional.

**Expected Result:**
The field "I do not consider" does not have any marks.

**Visual Proof (screenshots, videos, text):**
![2023-09-14_20-00-04](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/6de2730d-a869-4cc6-9fe3-85f17e28c3db)

**Severity:**
Minor (S4)

**Comment by ed9ward** [comment]
Tested
