### ISSUE TITLE
[BUG] The field "Email" accepts symbols that are not provided for in the validation document on page "Sign Up"

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#447]
**Description:**
The field "Email" allows data entry using the Cyrillic alphabet on page "Sign Up"

**Environment:**
OS - Android
Version - 12 SP1A.210812.016

**Steps to reproduce:**

1. Open app
2. Type invalid data in the field "Email" (ЯЮЄ@test.ua)
3. Type valid data in the field "Password"
4. Press button "Sign Up"
5. Pay attention that the user is redirected to registration steps

**Actual Result:**
The field "Email" allows data entry using the Cyrillic alphabet on the page "Sign Up"

**Expected Result:**
The data that can be entered into the field "Email" should be required to the criteria that are written in the [validation document](https://docs.google.com/spreadsheets/d/1OM1GunJPbMa6u0Dn4rm9Cgh32PBfMNOxv588UZYBM_4/edit?usp=sharing)
**Visual Proof (screenshots, videos, text):**

**Severity:**
Critical (S2)
![кирилиця](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/4b3e86fa-5608-4f83-87e2-557f115df1bf)

https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/782ffdb0-402d-49ae-ae9c-af6127d9e101

**Comment by ed9ward** [comment]
Tested
