### ISSUE TITLE
Create candidate details screen

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#455]
THIS SHOULD BE DONE FIRSTLY: https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/541
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/103518438/aff29af9-b3a3-434a-ad4f-6b009a746ad6)

**User story:**

As an Employer, I want to be able to see Talent profiles, so that I can review basic information and make decisions about the contact with Talent

Acceptance criteria:
1. On the top of the page must show breadcrumb trail links
2. The content area of the page must contain:
- the information about the job title that the user chose
- the information about the size of salary expectation that the user chose
- the information about the current location that the user chose
- the information about the years of experience that the user chose
- the information about the English level that the user chose
- the information about the employment type that the user chose
- the information about the vacancies that the user does not consider
- the information about the Talent's date account publishing
- the user’s cover letter
- active tabs: Scores & skills, Feedbacks, Project
- the active button “Contact candidate” 
3. The tab “Scores & skills” must contain:
- the BSA badges with labels and scores
- the information about the hard skills that the user chose
4. The tab “Feedbacks” must contain HR comments about the Talent's skills:
- information about personality type, the selected components are displayed as tags
- HR badges, the selected components are displayed as tags
5. The tab “Project” must contain information about Talent’s project that includes data about the duration of the project, composition and specialization of the team, the scope of the project, project preview
6. The layout must match the design posted on Figma (specified above)

**Comment by Oleksandrra** [comment]
![Screenshot_2023-09-28-12-59-46-365_com bsa_talents-edit](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/940891ca-d103-48cc-9877-0e21356d011d)
tested
