### ISSUE TITLE
Create contact candidate screen

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#456]
For mobile let's create it as separate screen, not modal window 

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/103518438/fab77044-cc66-4bc5-86fa-6fc05b4f2989)

User story

As an Employer, I want to contact Talent so that I can be able to see full information about Talent and to share the link to the vacancy

Acceptance criteria:

1.The content area of page must contain:

- the title “Contact candidate”
- the subtitle “Send the first message to the candidate”
- the button “Close” in the right-up corner
- the fields to type the link to a vacancy with the title “Add link to the vacancy”
- the active link “Add more link”
- the field to type the message with the title “Write a message”
- the checkbox “Save as template”
- the button “Sent message”

2. The information that can be entered in the  fields “Add link to the vacancy”,  “Write a message”  should required to the criteria that  are written in the validation document

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695220853758729

**Comment by Oleksandrra** [comment]
after https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/455

**Comment by Oleksandrra** [comment]
tested
![Screenshot_2023-09-28-13-16-29-758_com bsa_talents-edit](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/7b7a0457-6a5a-4413-8da5-ce22628fc21c)
