### ISSUE TITLE
[BUG] Project link field bugs

### ISSUE THREAD

**Issue by ed9ward** [BinaryStudioAcademy/bsa-2023-bsa-talents#457]
**Description:**
Error messages appear on the empty Project link field when going to the next step

**Environment:**
Win 11, Chrome 116

**Steps to reproduce:**
1. Go to Step 3
2. Fill in all fields
3. Add two Project links and fill only one of them, leave the other empty
4. Go to the next step

**Actual Result:**
1. Error message appears for each empty Project link field
2. Project link has no delete button
3. Project links haven't updated if user saved one and then went back and delete it

**Expected Result:**
1. No errors when leaving the Priojct link empty
2. Project link should have a delete field function to remove unnecessary fields.
3. Project links should always updates when go to the Next Step

**Visual Proof (screenshots, videos, text):**
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/88102cb5-5b59-49b0-8b42-803863d8bbe7)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/062e9a2a-7bab-4284-9f5f-0001dce69266)

**Severity:**
Medium

**Comment by MChornomaz** [comment]
It will be fixed after merging #350 . I fixed it there

**Comment by ed9ward** [comment]
Added visuals

**Comment by ed9ward** [comment]
Tested
