### ISSUE TITLE
Create admin user verification layout

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2023-bsa-talents#459]
Don't add checkboxes

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/105710998/bd1e31e2-7d20-4ae9-b162-cc3b986ae1d7)

User story:
As an Admin, I want to be able to see the page of user verification, so that I can review all the information can make decisions about approving/denying account

Acceptance criteria:

1. The page must contain:
- the header
- the sidebar with the logo site
- the title “Verification”
- the content area
2. The content area has two parts: a user profile review, a sidebar with tabs
3. The sidebar of the content area must contain:
- tab with the title “Talents”, where the Admin can see a list of Talent’s profiles, that were sent for verification
- tab with the title “Employers”, where the Admin can see a list of Employer's profiles, that were sent for verification
- near the title, each of the tabs must be a quantity indicator of the profile, that sent for verification
4. The user profile review part of the content area must contain:
preview of the profile chosen from the list account, which includes the user’s photo and full name
5. The active buttons “Deny” and “Next step” are placed under the review part of the content area

**Comment by anna9314** [comment]
Tested
