### ISSUE TITLE
Create profile component in admin user verification

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2023-bsa-talents#460]
![Image](https://user-images.githubusercontent.com/105710998/268266406-8522f485-702c-4f4c-83ac-1d51e6ee2824.png)

Acceptance criteria:

1. The user profile review part of the content area must contain:
- tab “Profile”
- tab “CV and contacts”
- tab “Characteristics”

2. The content area of the tab “Profile” must contain the fields with the next titles:
- “Profile name”
- “Salary  expectations”
- “Experience”
- “Current location”
- “Employment type”
- “Level of English”
- “I do not consider”
- “Preferred language of communication”
- “Project links”

3. The sidebar of the tab “Profile” must contain:
- BSA badges element
- Hard skills element

4. The fields and elements listed above will show information, that the user filled in during the registration steps

**Comment by Monyster** [comment]
Is this normal?
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/42421305/38476b53-4439-4642-9152-cf6b7f73b804)

I decide to do next
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/42421305/701e58fb-14c4-4752-9eb7-26e3961f7f3a)

**Comment by Oleksandrra** [comment]
@Monyster do you mean alignment? yes, for my opinion looks better

**Comment by Monyster** [comment]
Why badges lower than the left side?
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/42421305/aa218cbd-67b0-4194-84c8-39505846175f)

**Comment by Oleksandrra** [comment]
@Monyster I think, when You will have some draft, we can clarify it with PO or coaches
Also, the reason can be, that high of badges and hard skills elements is low than the common high of all the fields on the right side

**Comment by Monyster** [comment]
For example, if I have left content height 1000px and a right content height 300px. Where do I need to align this right side?
- In the center 
- Or stick it to the top

**Comment by Oleksandrra** [comment]
In the center

**Comment by Oleksandrra** [comment]
it's my personal opinion) can you send how the looks align in the center and the top?

**Comment by Monyster** [comment]
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/42421305/ad016fdd-0144-4956-8cc0-31733d1b8293)
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/42421305/796eaead-de92-4bbf-8efd-de57a9c40d7e)

**Comment by Oleksandrra** [comment]
Thanks) I like this
https://user-images.githubusercontent.com/42421305/268396103-ad016fdd-0144-4956-8cc0-31733d1b8293.png

**Comment by kimokimo882** [comment]
Excellent new work

**Comment by anna9314** [comment]
tested
