### ISSUE TITLE
Create characteristics component in admin user verification

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2023-bsa-talents#461]
**User story:**
As an admin, I want to have a characteristics tab on the verification screen, so that I can choose badges and add them to the candidate's profile

**Acceptance criteria:**
- Feedback block should have feedback from each week, Feedback from BSA coach project, HR interview results
- When the admin clicks on Feedback - the comment should be displayed from the right side
- Admin should be able to choose Personality type, Soft skills of a talent
- Personality type dropdown field should be multichoice and have options: Doer / Connector / Thinker
- Soft skills dropdown field should be multichoice and have options: Communicative, Collaboration, Problem-solving, Leadership, Creative, Proactive
- Soft skills and Personality type should have placeholder “Option”

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/105710998/6d300a7b-7be3-4305-96cd-e129a6de260c)

**Comment by Monyster** [comment]
"There should be “Deny” and “Next step” buttons"

Maybe buttons should be somewhere in the layout, not in this task?


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/42421305/dbab3798-e53d-4570-b514-b0ad6c579774)

**Comment by anna9314** [comment]
Yep, the “Deny” and “Next step” buttons" for the layout task. Corrected AC

**Comment by anna9314** [comment]
Tested
