### ISSUE TITLE
Reset user's data on logout

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#463]
**Acceptance criteria:**
- All entered user's data should be reset when the user logout
- All data from step 01: Profile name, Salary expectations, Job title, Experience, Current Location, Employment type, Briefly tell employers about your experience.
- All data from step 02: selected checkboxes (Communication score, Working with team score, Punctuality)
- All data from step 03: Hard Skills, Level of English, I do not consider, Preferred language of communication, Project links.
- All data from step 04: profile photo, Full name, Phone number, LinkedIn profile, CV

**Comment by ed9ward** [comment]
Tested
