### ISSUE TITLE
Create CV and Contacts component in admin user verification

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2023-bsa-talents#464]
Right now we don't have design so you can put some placeholders there

**User story:**
As an admin, I want to have a CV and Contacts tab on the Verification screen, so that I can see the candidate’s contact information

**Acceptance criteria:**

- There should be displayed all information which talent fills in on the onboarding step 03
- There should be displayed profile photo of the candidate, full name, phone number, Linkedin link and CV
- Admin should be able to go to the LinkedIn profile by clicking on the link
- Admin Should be able to open the CVs of candidates

**Comment by nikita-remeslov** [comment]
Link PR

**Comment by anna9314** [comment]
Tested
