### ISSUE TITLE
Create candidate cabinet for profile updating

### ISSUE THREAD

**Issue by savinaDaria** [BinaryStudioAcademy/bsa-2023-bsa-talents#468]
Cabinet will be in user dropdown menu

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/58756139/173accb6-5f08-41c1-872c-1d745969866d)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/58756139/70ace6ab-f45b-4c87-874e-73eec3bdb222)

**User story**

As a Talent, I want to have access to my personal cabinet, so that I can edit my personal info

**Acceptance criteria:**
1. The user can go to the page of the edit personal information after choosing this option in the dropdown component under the user avatar
2. The information displayed on this page must meet the information that the user filled in during the registration
3. The content area of the page must contain:
- the title “Your profile”
- the tabs “Profile”, “BSA badges”, “Skills and projects”, “CV and contacts”, “Hiring”
- the active buttons “Save”, “Edit” 

4. The content area of the tab “Profile” must contain the fields with the next titles:
- “Profile name”
- “Salary  expectations”
- “Job title”
- “Experience”
- “Current location”
- “Employment type”
- “Briefly tell employers about your experience” 

5. The data that can be entered into the fields “Profile name”,  “Salary  expectations”
“Job title”, “Briefly tell employers about your experience”  should meet the criteria that are written in the [validation document](https://docs.google.com/spreadsheets/d/1OM1GunJPbMa6u0Dn4rm9Cgh32PBfMNOxv588UZYBM_4/edit?usp=sharing).

**Comment by Oleksandrra** [comment]
All these fields are from step 1 of registration. If Talent can edit this information, we need to add also “Briefly tell…”. I will clarify this point

**Comment by ed9ward** [comment]
Tested
