### ISSUE TITLE
Create employer cabinet for profile updating

### ISSUE THREAD

**Issue by savinaDaria** [BinaryStudioAcademy/bsa-2023-bsa-talents#469]
**User story:**
As an employer, I want to have a profile screen, so that I can edit my profile information and submit it for verification to the admin

**Acceptance criteria:**

- There should be a user avatar in the right upper corner 
- When a user clicks on avatar the menu with logout appears
- There should be a sidebar on the left side with the Chats and Candidates buttons
- There should be tabs: Profile and Hirings
- Profile tab should have: Full name, Your position, Linkedin profile, Company name field, Company website,  Briefly tell about your company and it’s value fields [Fields validation](https://docs.google.com/spreadsheets/d/1OM1GunJPbMa6u0Dn4rm9Cgh32PBfMNOxv588UZYBM_4/edit#gid=0)
- Hirings tab should display a list of candidates that which employer hired
- There should be fields for profile photo and company logo

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/58756139/e0cb3cd3-d933-4f44-abb6-ba27edf753b0)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/58756139/de65632d-1adb-4c21-8340-f45c6a399108)

**Comment by ed9ward** [comment]
Tested
