### ISSUE TITLE
Add overlay view for onboarding steps

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#471]
Currently, when the user presses next on each step, we have a backend request and no overlay view. We need to add it, to disable pressing any buttons, while the request is loading

**Comment by katerynakostikova** [comment]
Build in 20 minutes

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695115227854739

**Comment by ed9ward** [comment]
Tested
