### ISSUE TITLE
Change min symbols for Step1 description field

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#472]
- [x] Rename "Briefly tell employers about your experience" field to "Introduce yourself"
- [x] Change the placeholder to "Candidates who share more about their experience have higher chances of getting a job offer." (only if it'll be shown well on mobile view)
- [ ] Change the min length validation to 100 symbols.
- [ ] Change the validation message according to the new rule.

![Image](https://user-images.githubusercontent.com/8355821/268628475-e440d6d7-f385-4096-938b-72d8394bd879.png)

**Comment by ed9ward** [comment]
Added new description

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695200050965939

**Comment by ed9ward** [comment]
Need to add text break to a new line


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/d54c2dab-fbef-4328-a022-4b9dc6f7b6b2)

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695289114650759

**Comment by ed9ward** [comment]
Tested
