### ISSUE TITLE
[BUG] The progress bar isn't displayed continuous

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#484]
**Description:**
The progress bar isn't displayed continuous when the resolution is 2340x1080

**Preconditions:**
The BSA talent app is open

**Environment:**
Android 13  
Samsung Galaxy A52 (2340x1080)

**Steps to reproduce:**
1. Enter a valid email and password
2. Click on Sign up
3. Pay attention to the progress bar

**Actual Result:**
The progress bar isn't displayed continuous when the resolution is 2340x1080

**Expected Result:**
The progress bar is displayed continuous 

**Visual Proof (screenshots, videos, text):**
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/166a5b63-96ef-473c-bd51-022540b8c84d)

**Severity:**
Minor (S4)

**Comment by nikita-remeslov** [comment]
Link PR

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695117470520269

**Comment by ed9ward** [comment]
Tested
