### ISSUE TITLE
[BUG] Badge's layout isn't displayed according to design on the Scores & Skills tab

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#486]
**Description:**
The badge's layout isn't displayed according to design on the Scores & Skills tab when the resolution is 2340x1080

**Preconditions:**
The BSA talent app is open

**Environment:**
Android 13
Samsung Galaxy A52 (2340x1080)

**Steps to reproduce:**
1. Sign up
2. Go to step 05
3. Pay attention to the badge's layout

**Actual Result:**
1. Scores go out of badges
2. The word "Punctuality" breaks

**Expected Result:**
All badges are displayed according to the design
Scores don't go out of badge's blocks
Words don't break

**Visual Proof (screenshots, videos, text):**
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/9d87f2ce-0300-4750-a721-197516ef61f6)

**Severity:**
Major (S3)

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695117470520269

**Comment by ed9ward** [comment]
Tested
