### ISSUE TITLE
[BUG] The information about chosen hard skills is displayed to the user, which opens the page "Step 03/05" for the first time

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#487]
**Description:**
The information about chosen hard skills is displayed to the user, which opens the page "Step 03/05" for the first time

**Preconditions:**
Open  http://bsa-talents.us-east-1.elasticbeanstalk.com/sign-up

**Environment:**
 OS - Windows 10 Pro
 Browser - Google Chrome
 Version - 116.0.5845.142
Browser -Firefox
Version 117.0.1 (64-біт)

**Steps to reproduce:**

1. Enter the valid data in the fields “Email” and “Password”
2. Choose radiobutton “I’m looking for a job”
3. Click on the button “Continue”
4. Fill in mandatory fields on page "Step 01/05", press  “Next”
5. Press “Next” on the page "Step 02/05"
6. After redirecting to the page "Step 03/05" pay attention that the information about chosen hard skills is displayed before the user made the choice

**Actual Result:**
The  information about chosen hard skills is displayed before the user made

**Expected Result:**
All fields are empty before the user makes the choice

**Visual Proof (screenshots, videos, text):**
https://drive.google.com/file/d/1rJhAZNro06Xm_E89JIQU8UDLm7gd57Go/view?usp=sharing

**Severity:**
Critical (S2)

**Comment by nika-sirak** [comment]
It is NOT a bug, it is temporary solution

**Comment by ed9ward** [comment]
Tested
