### ISSUE TITLE
[BUG]The chosen country does not display in the field "Current location" when user uses dark mode 

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#498]
**Description:**

The chosen country does not display in the field "Current location" when user uses dark mode 

**Preconditions:**
App build 18/09/23 11:16
**Environment:**

OS - Android
 Version - 12 SP1A.210812.016
Setting of screen mode - dark mode

**Steps to reproduce:**

Open the app
Sign Up with valid data, press “Sign Up”
Fill in the required fields on the page “Step 01/05”
Choose country in the field "Current location"
Pay attention that chosen country does not display in the field "Current location"
Press button “Next”
Pay attention that validation error about empty field "Current location" does not appears, user is redirected to the next step

**Actual Result:**
The chosen country does not display in the field "Current location". The validation error about empty field "Current location" does not appears, user is redirected to the next step

**Expected Result:**
The chosen country displays in the field "Current location"

**Visual Proof (screenshots, videos, text):**

**Severity:**

Critical (S2)

https://drive.google.com/file/d/1449Rl9Ax7LzFJBZiyThrv5nC9B2QWc-v/view?usp=drivesdk

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695200050965939

**Comment by ed9ward** [comment]
Tested
