### ISSUE TITLE
Create Select component

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2023-bsa-talents#5]
Create a custom dropdown component which we will reuse in the project

User should be able to select one option or multiple options

![Image](https://user-images.githubusercontent.com/105710998/261578768-dc416979-da83-41ef-ab3b-e4897562848d.png)

https://mui.com/material-ui/react-select/

**Comment by MChornomaz** [comment]
For the moment I created component but didnt use constants for colors and typography for now, need to get this data from others developers tommorow. For the moment I left 
// eslint-disable-next-line @typescript-eslint/no-unused-vars
for "theme" constant, where I will get this data tommorow
