### ISSUE TITLE
Add verification message after onboarding steps for both roles

### ISSUE THREAD

**Issue by ed9ward** [BinaryStudioAcademy/bsa-2023-bsa-talents#500]
After a user completes his onboarding steps the “Waiting for approval” label appears near the avatar on the top, like in Djinni
In this state, until he is verified, he won't be able to reach other pages than the Preview of his profile.

![Image](https://user-images.githubusercontent.com/8355821/268311141-efd102c9-6a97-46b2-b409-7cf9ab68ee63.png)

**Comment by lavandosya** [comment]
Will need to connect with the userDetails store after adding the "publish now" logic after the preview page.
