### ISSUE TITLE
Mobile - Add verification message after onboarding steps for both roles

### ISSUE THREAD

**Issue by ed9ward** [BinaryStudioAcademy/bsa-2023-bsa-talents#502]
After a user completes his onboarding steps the “Waiting for approval” label appears near the avatar on the top, like in Djinni
In this state, until he is verified, he won't be able to reach other pages than the Preview of his profile.

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/6a18b3a2-8405-44d8-a836-8e9a1eb1c95d)

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695650155932399

**Comment by Oleksandrra** [comment]
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/a1ba3d78-4a5f-4b8c-9051-cb2c1e9090fa)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/913507de-03f1-4499-881a-ec9efabbedfa)

tested
