### ISSUE TITLE
[BUG] Preview page UI bugs

### ISSUE THREAD

**Issue by ed9ward** [BinaryStudioAcademy/bsa-2023-bsa-talents#506]
**Description:**
The preview page has some UI bugs

**Environment:**
Win 11, Chrome 116

**Steps to reproduce:**
1. Fill in all data on the onboarding steps
2. Go to the Preview page

**Actual Result:**
1. Experience is shown just as a number
2. Cover letter is shown as plain text, without line breaks
3. Cover letter is shown without spoiler hiding
4. User can't see where he will be redirected when clicking on the Repository link button

**Expected Result:**
1. Experience must be in the same format as on Step 1 (0,5 years for example)
2. Cover letter should display text as it was typed on Step 1
3. Cover letter should hide text after three lines under spoiler. On click Read more this spoiler reveals all Cover letter hidden text.
4. Repository link should be displayed on hover the link which the user will be redirected to(like on the screenshot below)

**Visual Proof (screenshots, videos, text):**
![Image](https://user-images.githubusercontent.com/8355821/268624575-0f2c5282-eac3-45a8-9746-108879bf9ccb.png)
![Image](https://user-images.githubusercontent.com/8355821/268626975-d5212906-1f6f-43c7-b4b5-bee71094d2fc.png)
![Image](https://user-images.githubusercontent.com/8355821/268624367-cd942744-f10b-4a1f-ae04-78b05a1f0655.png)

**Severity:**
Medium

**Comment by ed9ward** [comment]
Skills and Languages aren't displayed when filled in all data and went to Preview for the first time.
But not sure for now if this is Preview problem, or the data saving after Step 3.

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/e4611922-8723-41cf-8ece-a62f14754b07)

**Comment by nika-sirak** [comment]
Languages are fixed. Hard Skills is problem on Step3 - still in progress

**Comment by ed9ward** [comment]
Still should fix this. Spoiler isn't working. It just adds three dots at the end.

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/49dfed43-f378-4939-9839-2c92d9e6f977)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/c317fc66-83be-4b14-b6de-83bb7322a454)

**Comment by ed9ward** [comment]
Tested
