### ISSUE TITLE
Change Step 1 Cover letter field

### ISSUE THREAD

**Issue by ed9ward** [BinaryStudioAcademy/bsa-2023-bsa-talents#507]
- [x] Rename "Briefly tell employers about your experience" field to "Introduce yourself"
- [x] Change the placeholder to "Candidates who share more about their experience have higher chances of getting a job offer."
- [x] Change the min length validation to 100 symbols.
- [x] Change the validation message according to the new rule.
- [x] Reduce margin from field name to text field to be same as other fields(screenshot in comments)
- [x] Disable the ability to change width of the field, left only stretch to bottom

![Image](https://user-images.githubusercontent.com/8355821/268628475-e440d6d7-f385-4096-938b-72d8394bd879.png)

**Comment by nika-sirak** [comment]
It's not a cover letter. The cover letter shouldn't be general. We write it individually for a specific company. It could be a 'summary' or 'about' but not a cover letter.

**Comment by Simpsonkk** [comment]
or motivation letter but as for me cover letter is also possible

**Comment by ed9ward** [comment]
I saw some analogs have these names of the same field: Introduce yourself, About you, Summary

I guess we could pick any of the list

**Comment by Simpsonkk** [comment]
the task was postponed at the meeting and the decision will be made later

**Comment by ed9ward** [comment]
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/63847868-5093-4d7a-8643-e7221aba57f7)

**Comment by ed9ward** [comment]
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/09767120-ed8b-452e-ab47-16716f4a1cef)

**Comment by ed9ward** [comment]
Tested
