### ISSUE TITLE
Create error handling

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2023-bsa-talents#51]
Add store middleware
Create notification service using https://www.npmjs.com/package/react-toastify

**Comment by JemiJe** [comment]
should we use separate directory for `toast` from 'react-toastify', in future customisation for example? and where to put it? Now, I have only error service middleware (which calls that `toast`) and `Notifications` component which returns customized `ToastContainer`

**Comment by anton-otroshchenko** [comment]
You should create a Toast component where we can later put our custom styles. Also create a service where you can call not only toast.error() but also toast.success(), etc. You can then use this service in store middleware like this 
`notificationService.error(yourError)`

**Comment by anton-otroshchenko** [comment]
You can later add this Toast component in index file
