### ISSUE TITLE
Remove scroll lines from navigation and all screens

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#511]
Let's remove scroll lines to make our app more mobile friendly 

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/103518438/5053e260-6d23-454c-baf1-27d8151b94bb)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/103518438/4e22482f-8533-465e-af4d-c34cc24483c0)

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695117470520269

**Comment by ed9ward** [comment]
Tested
