### ISSUE TITLE
Add ability to view password during sign in/up

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#512]
Add ability (eye icon) to view password in sign in/up to improve UX.

**Comment by katerynakostikova** [comment]
Build in 20 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695208107676209

**Comment by anna9314** [comment]
Tested
https://prnt.sc/Jaz7Jvmsnvp9
https://prnt.sc/BwVWOyflywre
