### ISSUE TITLE
Connect search to API

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#516]
**Acceptance criteria:**

- Employer should be able to search for talents
- All talents who created profiles and were verified by admin should be displayed on the search page
- Employer should be able to search using filters: Job Title, Hard Skills, Years of experience, BSA Characteristics, BSA Badges, BSA Project, Location, Level of English, Employment Type.
- Employer should be able to search using: basic search and full-text search 
- All talents by the selected request should be displayed

**Comment by nika-sirak** [comment]
- [x] Employer should be able to search for talents
- [x] All talents who created profiles and were verified by admin should be displayed on the search page
- [x] Employer should be able to search using filters: Job Title, Hard Skills, Years of experience, BSA Characteristics, BSA Badges, BSA Project, Location, Level of English, Employment Type.
- [x] Employer should be able to search using: basic search and full-text search
- [x] All talents by the selected request should be displayed

**Comment by nika-sirak** [comment]
BSA Badges are removed. BSA Characteristics and BSA Project are not working on the server side, so I can't implement them.
Employer should be able to search using: basic search and full-text search will be implemented later, not in this ticket.

**Comment by nika-sirak** [comment]
I'm waiting for hard skills PR so Hard Skills is still in progress

**Comment by anna9314** [comment]
tested
