### ISSUE TITLE
Сombine close/opened candidate page

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#517]
**Acceptance criteria:**

1. - Talent’s contact information should be hidden before a talent approves and shares contacts with the employer
2. - When talent’s account is hidden, there should be displayed: profile name, academy’s score, skills, HR’s comments, brief description about experience, salary expectations, Location, Year of Experience, Level of English, Employment type, Work preferences
3. - When talent shares his/her contact information with the employer on the Candidate’s page should be displayed: full name, email, phone number, repository link
4. - When the employer clicks on the read me button on the Search candidate's page he/she should be redirected to the close/opened Candidate's page (if the candidate doesn't approve and share contact information with this employer - close page,  if the candidate  approves contact and shares contact information with this employer - opened page)
5. - When the employer clicks on the candidate's full name in the Chat screen he/she should be redirected to the opened Candidate's page
6. - Connect close/opened candidate page to API

Use components from this [link](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/pull/228#issuecomment-1709190036)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/6449707a-65fa-47d2-8058-8fb14d8b6fde)

**Comment by Simpsonkk** [comment]
Comment has been deleted

**Comment by savinaDaria** [comment]
Partially implemented in #625 (closed page navigation from search page)
Contains code from PRs in progress, so I leave it as draft for now

ToDo: 

- after implementing of DB table with **candidate-employer relations** add **opened candidate page** handling . I guess depends on #638 
- check chat links, where also navigation to candidate page should be added

**Comment by savinaDaria** [comment]
#614

**Comment by savinaDaria** [comment]
Opened page in search results is implemented in this PR #702

**Comment by Oleksandrra** [comment]
tested


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/b98be8df-9b50-4018-8974-5f464d5e2ffc)
