### ISSUE TITLE
Connect Admin approval of the Talent’s profile to API

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#520]
As an Admin, I want to review the Talent’s profile, so that I can make decisions about the approval or denial of the publishing of the profile

Acceptance criteria:

1. After  the clicking on tab with the title “Talents” a list of Talent’s profiles, that were sent for verification opens
2. After the clicking on selected profile from the list item, the preview of the user’s profile opens
3. The preview of the user’s profile contains information, that the user filled in during the registration steps
4. After  the clicking on tab “Characteristics” Admin can add:
- soft skills (admin can choose from the list and it will be shown on the Candidate's page) based on feedback
- personality type based on the feedback (admin can choose from the list and it will be shown on the Candidate's page) 

**talent's soft skills and personality type will be chosen by admin (based on BSA characteristics) and attached to the talent card, BUT it is visible only to employers, not students**

5. After clicking on the button  “Deny” the dialog box opens. This box has the subtitle “Please specify the reasons you deny the verification”, contains the field for typing text, the active button “Cancel”, the active button “Ok”
6. After clicking on the button “Approve” the user’s profile is published

**Comment by anna9314** [comment]
Tested
