### ISSUE TITLE
Connect Admin approval of the Employer’s profile to API

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#521]
As an Admin, I want to review the Employer’s profile, so that I can make decisions about the approval or denial of the publishing of the profile

Acceptance criteria:

1. After clicking on the tab with the title “Employers” a list of Employer’s profiles, that were sent for verification opens
2. After clicking on the selected profile from the list item, the preview of the user’s profile opens
3. The preview of the Employer’s profile contains information, that the user filled in during the registration
4. After clicking on the button  “Deny” the dialog box opens. This box has the subtitle “Please specify the reasons you deny the verification”, contains the field for typing text, the active button “Cancel”, the active button “Ok”
5. After clicking on the button “Approve” the user’s profile is published

**Comment by anna9314** [comment]
Tested
