### ISSUE TITLE
Connect Chat to API

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#522]
- [x] 1. The chat screen should contain two parts: a chat sidebar on the left side of the screen and a main chat block
- [x] 2. The header of the main chat block contains the user avatar, full name, and status (online/offline)
- [x] 3. The chat sidebar contains the field for the search and list of chats
- [x] 4. After typing text in the field for the search a list of users whose name contains the entered text appears under the search field
- [x] 5. After clicking on the selected item from the chat  list it becomes a highlighted
- [x] 6. After clicking on the selected item from the chat list opens the main chat block between the user and the Employer/Talent
- [x] 7. The main chat block contains the field for typing text, the previous history of chat, a block with information about potential employer (for Talent)
- [x] 8. Allowed length for text area – up to 1000 characters. Users can not type and paste more than 1000 characters. When a user enters more than 1000 characters the validation message about the maximum size is displayed  and the entered text not sending
- [x] 9. The message is sent after pressing the button “Enter” or on the Send icon
- [x] 10. After sending, the message displayed on chat history without page refresh for both users
- [ ] 11. After sending, the message displayed on chat history with “unread” ticks status for the user, who sends a message, without page refresh
- [ ] 12. After reading a message by another user, the message status changes to “read” for the user, who sends a message, without a page refresh
- [x] 14. After choosing another item from the chat list, the history of this chat is saved for both users
- [ ] 15. After pressing the button “Share your contact and CV” for Employer  full information about Talent becomes able
- [ ] 16. After pressing the button “The company already hired me” the notification is sent to Admin
- [x] 17. After clicking on the Employer website link, Talent is redirected to this website

**Comment by ed9ward** [comment]
Tested
