### ISSUE TITLE
Change to disable the tabs  and remove link to the page "Candidates" and "Chat" from sidebar until the user's account approval by Admin

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#525]
The icons of tabs are displayed in the sidebar, but as disabled
After hovering the cursor on these tabs the cursor is changed from pointer on default  

Talent
Search - on default doesn't have access to Search (tab "Candidates)
Chat - doesn't have access until Admin approval
Employer
Search - doesn't have access until Admin approval 
Chat - for  users with subscribe

![IMG_20230920_141500](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/3600bf1c-6d2c-4431-aba1-e79b6bd007a2)
![IMG_20230920_141517](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/f437d744-da41-4511-bbb5-3e4a97958554)
![IMG_20230920_141531](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/2975bc78-3fc1-49d5-ac07-72ac1546bee3)

**Comment by nikita-remeslov** [comment]
@Oleksandrra I think we can remove only links

**Comment by anna9314** [comment]
Tested
