### ISSUE TITLE
Create endpoint to get talents/employers in admin dashboard

### ISSUE THREAD

**Issue by MaksymGavatuk** [BinaryStudioAcademy/bsa-2023-bsa-talents#527]
Create endpoint to get short data for this list
Please implement GET endpoint with querystring param userType for employers and talents to not to duplicate code

- [x] create query to get only necessary data
- [x] create DTO
- [x] create repository/service methods
- [x] create endpoint

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/93519384/8ab5c3f2-ede3-41ce-a81b-0b34d8379b5a)

**Comment by ed9ward** [comment]
Tested
