### ISSUE TITLE
Implement deny&approve backend logic

### ISSUE THREAD

**Issue by MaksymGavatuk** [BinaryStudioAcademy/bsa-2023-bsa-talents#528]
Implement backend logic for deny&approve action

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/93519384/54b1992e-73fd-4233-97b1-aae27721e20b)

Also need to save reason

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/93519384/79557193-b5d6-4b4d-8dd1-378c91c13985)

Approve:

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/93519384/5ed44938-e619-42be-a16e-135916cf5b1e)

**Comment by anna9314** [comment]
Tested
