### ISSUE TITLE
Add Talent Profile screen

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#530]
I see it as a screen, with top navigation for each tab 
[https://reactnavigation.org/docs/material-top-tab-navigator/](https://reactnavigation.org/docs/material-top-tab-navigator/)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/103518438/369fd9ef-dfa3-406c-810c-34b9abc6f0e0)

User story

As a Talent, I want to have access to my personal cabinet, so that I can edit my personal info

Acceptance criteria:

1. The content area of page must contain:

- the title “Your profile”
- the tabs “Profile”, “BSA badges”, “Skills and projects”, “CV and contacts”, “Hiring”
- the active buttons “Save”, “Edit” 

2. The content area of the tab “Profile” must contain the fields with the next titles:

- “Profile name”
- “Salary  expectations”
- “Job title”
- “Experience”
- “Current location”
- “Employment type”
- “Briefly tell employers about your experience” 

3. The data that can be entered into the fields “Profile name”,  “Salary  expectations”
“Job title”, “Briefly tell employers about your experience”  should meet the criteria that are written in the [validation document](https://docs.google.com/spreadsheets/d/1OM1GunJPbMa6u0Dn4rm9Cgh32PBfMNOxv588UZYBM_4/edit?usp=sharing).

**Comment by nikita-remeslov** [comment]
Link PR

UPDATE: I was looking in the wrong place!

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695824001443929

**Comment by Oleksandrra** [comment]
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/a499291c-a930-4eee-8252-35faa9d43b3b)

tested
