### ISSUE TITLE
Add Employer Profile screen

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#531]
**User story:**
As an employer, I want to have a profile screen, so that I can edit my profile information and submit it for verification to the admin

**Acceptance criteria:**

- Should be displayed the name of the page "My profile"
- On the top of the page profile photo (required) and company logo should be displayed 
- The content area of the “Profile” page must contain the fields with the next titles: 
 Full name (required), 
Your position (required), 
Linkedin profile (required), 
Company name field (required), 
Company website (required), 
Briefly tell about your company and it’s value (required)

- [Fields validation](https://docs.google.com/spreadsheets/d/1OM1GunJPbMa6u0Dn4rm9Cgh32PBfMNOxv588UZYBM_4/edit#gid=0)
- There should be a "Save" button under the "Briefly tell about your company and it’s value" field

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/103518438/1813726d-eece-49fc-be5e-5a3c483f3651)

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695450976367339

**Comment by ed9ward** [comment]
Tested
