### ISSUE TITLE
[BUG] Sign Up page UI bugs

### ISSUE THREAD

**Issue by ed9ward** [BinaryStudioAcademy/bsa-2023-bsa-talents#537]
**Description:**
Sign up\Sign In pages have some visual bugs

**Environment:**
Win 11, Chrome 116

**Steps to reproduce:**
1. Open Sign up page
2. Select Talent's radio button

**Actual Result:**
1. Error message about unselected Terms shown visually as a backend error
2. "*" symbol divided from text with a space
3. Radiobuttons have a wrong alignment

**Expected Result:**
1. We should use the hint and red outline on BSA Terms checkbox in the same way as everywhere else in the app
2. All required fields on Sign In and Sign Up pages should have "*" symbol next to them without space (Email*)
3. Radibuttons should be aligned left with the checkbox

**Visual Proof (screenshots, videos, text):**
![Image](https://user-images.githubusercontent.com/8355821/268953579-13cb5e0a-5159-4d68-8cb0-02b9011f3ca9.png)

**Severity:**
Medium

**Comment by lavandosya** [comment]
Done work in one PR #567

**Comment by ed9ward** [comment]
Tested
