### ISSUE TITLE
Replace candidate screen with real data and connect filters

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#541]
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/103518438/384af833-e03a-4bb6-afb2-e2d21bcb0d45)

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695717724319719

**Comment by Oleksandrra** [comment]
BR [The Employer can see Talant`s full name in search result#730](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/730)

**Comment by anna9314** [comment]
Tested
Filter button doesn't work(

**Comment by mskmee** [comment]
@anna9314  I will make it today/tommorrow

**Comment by anna9314** [comment]
and we have this strange bug
[[BUG] The second letter of the abbreviation is displayed from lower case on the search page#755](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/755)
