### ISSUE TITLE
[BUG] The layout of the Employment onboarding page does not match with design

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#542]
**Description:**
The layout of the Employment onboarding page does not match with design

**Preconditions:**
The BSA app is open

**Environment:**
Android 13
Samsung Galaxy A52 (2340x1080)

**Steps to reproduce:**
1. Sign up with valid credentials
2. Fill out all steps
3. Go to the Preview page
4. Pay attention to the Employment onboarding page layout

**Actual Result:**
1. "Profile photo" validation message and "Company  photo" validation message  overlap each other
2. Briefly tell about your company field.... is not a required field
3. Spelling mistake for the "Briefly tell about your company" field  - "company and" 
4. Briefly tell.. field has no line breaks. All text typed in one line.
5. Linkedin profile named with typo. Hint does not match the others in app.
6. Company website has wrong hint.
7. Hint for Brielfy tell field is wrong
**Expected Result:**
1. "Profile photo" validation message and "Company photo" validation message don't overlap each other. Validation messages are readable 
2.  Briefly tell about your company field... is a required field
3. "Briefly tell about your company" field  doesn't have spelling mistakes
4. Briefly tell.. field should have line breaks to have the opportunity to type from a new line.
5. Linkedin filed should be named LinkedIn with a capital "I". Hint should be "Link format must be https://www.linkedin.com/in/"
6. Hint should be: Company website must be a valid URL.
7. Hint should be clear and understandable
**Visual Proof (screenshots, videos, text):**
![Screenshot_1](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/a27533ee-52d8-4c03-9377-7c0ed5205b23)
![Screenshot_2](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/ea265e0b-df8e-43c7-ba89-dfb4661d2225)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/5ab52824-cff8-4834-837b-86e502894628)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/391bc41a-8f9e-4022-bbd0-6e647bc5b365)

**Severity:**
Minor (S4)

**Comment by katerynakostikova** [comment]
Build in 20 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695385605021679

**Comment by ed9ward** [comment]
1. Photo hints still overlaps
2. LinkedIn name still with small "i". Should be LinkedIn.
3. Website should accept www.ex.ua. According to doc. Now it accepts only with http:// at the begining.

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695803236230149

**Comment by ed9ward** [comment]
Tested
