### ISSUE TITLE
[BUG] "Doesn't consider" is cut off on the talent preview page

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#546]
**Description:**
"Doesn't consider" is cut off on the talent preview page

**Preconditions:**
The BSA app is open

**Environment:**
Android 13
Samsung Galaxy A52 (2340x1080)

**Steps to reproduce:**
1. Sign up with valid credentials
2. Fill out all steps
3. Go to the Preview page
4. Pay attention to the "Doesn't consider"

**Actual Result:**
"Doesn't consider" is cut off on the talent preview page

**Expected Result:**
All selected "Doesn't consider" options are fully visible on the talent preview page

**Visual Proof (screenshots, videos, text):**
![Screenshot_4](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/33c5d8e9-c3bd-41c4-b922-faab9656da6f)
![Screenshot_5](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/9459c456-837e-4cd8-a845-342a87ae8d0d)

**Severity:**
Minor (S4)

**Comment by katerynakostikova** [comment]
Build in 20 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695385605021679

**Comment by anna9314** [comment]
Tested
https://prnt.sc/kGY_YVf1K7DE
