### ISSUE TITLE
Add DB diagram to readme.md

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2023-bsa-talents#547]
``` mermaid
erDiagram
   users {
      int id PK
      dateTime created_at
      dateTime updated_at
      text password_hash
      text password_salt
   }
   user_details {
      int id PK
      int user_id FK
   }
   user_details ||--|| users : user_id
```

Example: https://mermaid-js.github.io/mermaid-live-editor/edit#pako:eNp9UMsKwkAM_JUlZ_2BPYuXIgh6XCihCXbRbSWbotLtv7u21oOvnIaZDJlMD1VLDBZYVh4PgsE1xpguskTTjziPb9R4MttiJgiV9z6wqYQzpBL1Q-rO9CYpX9WcMcZLK1TWGOvvSsTT5BleYUpiRX_6l-lBjKuZXRe__Cktlyk9H7SzARYQWAJmZGE84UBrDuzAZkgoRweuGfIedtrubk0FVqXjBUxvPsubSSavrWymaseGhzs-yHcQ

**Comment by ed9ward** [comment]
Tested
