### ISSUE TITLE
[BUG]The information about the chosen Level of English is not displayed after the redirection from the page "Step 04/05" for the first time

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#551]
**Description:**
The information about the chosen Level of English is not displayed after the redirection from the page "Step 04/05" for the first time

**Preconditions:**
Open site http://bsa-talents.us-east-1.elasticbeanstalk.com/sign-up
Open "Step 03/05"

**Environment:**
OS - Windows 10 Pro

1. Browser - Google Chrome
Version - 116.0.5845.142
2. Browser -Firefox
Version 117.0.1 

**Steps to reproduce:**

1. Fill in mandatory fields on page "Step 03/05", press  “Next”
2. Fill in mandatory fields on page "Step 04/05", press “Back”
3. Pay attention that  the field “Level of English” is empty
4. Fill in the field “Level of English”,  press  “Next”
5. Fill in mandatory fields on page "Step 04/05", press “Back”
6. Pay attention that  the field “Level of English” is filled

**Actual Result:**
The information about the chosen Level of English is not displayed after the redirection from the page "Step 04/05" for the first time

**Expected Result:**
All information entered in mandatory fields is saved after the redirection to the next step

**Visual Proof (screenshots, videos, text):**
https://drive.google.com/file/d/1TjXRwcSUztT2jWto9o9_nsP7KZKdYigX/view?usp=drive_link

**Severity:**
Critical (S2)

**Comment by ed9ward** [comment]
Tested
