### ISSUE TITLE
Add  the checkbox "I agree to the BSA Talent Terms" on the page Sign Up for users, who chose the checkbox "I`m hiring"

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#559]
1.The ticking the checkbox is mandatory for registration
2.Marked *
3. The label near checkbox "I agree to the BSA Talent Terms" must contain link to the Terms 
4.If user leaves this checkbox empty, validation notification appears about the need to agree to the terms and the checkbox light red color
![IMG_20230920_134533](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/24fc49b7-17f1-4e6e-9d5a-33b5b5557292)

**Comment by lavandosya** [comment]
Done work in one PR #567

**Comment by anna9314** [comment]
Tested 
https://prnt.sc/93yVckNPxMEB
