### ISSUE TITLE
[BUG] Placeholder of the "Introduce yourself" is cut off on step 01 

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#570]
**Description:**
Placeholder of the "Introduce yourself" is cut off on step 01 

**Preconditions:**
The BSA app is open

**Environment:**
Android 13
Samsung Galaxy A52 (2340x1080)

**Steps to reproduce:**
1. Sign up with valid credentials
2. Pay attention to the placeholder of "Introduce yourself"

**Actual Result:**
Placeholder of the "Introduce yourself" is cut off on step 01 

**Expected Result:**
Placeholder of the "Introduce yourself" is fully visible on step 01 

**Visual Proof (screenshots, videos, text):**
![Screenshot_3](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/f1ce4dad-b2af-43c9-a33e-cd549e1da38f)

**Severity:**
Minor (S4)

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695289114650759

**Comment by anna9314** [comment]
Tested
