### ISSUE TITLE
[BUG] The request to receive user details at the first step of the onboarding flow is sent to the wrong Endpoint route

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#577]
**Description:**
The request to receive user details at the first step of the onboarding flow is sent to the wrong Endpoint route

**Preconditions:**
Open site http://bsa-talents.us-east-1.elasticbeanstalk.com/sign-up
Open Step 01/05

**Environment:**
OS - Windows 10 Pro
Browser - Google Chrome
Version - 116.0.5845.142
Browser -Firefox
Version 117.0.1

**Steps to reproduce:**

1. Open dev tools
2. Pay attention to the R

**Actual Result:**
http://bsa-talents.us-east-1.elasticbeanstalk.com/api/v1/user-details2370338f-4ec2-4089-ac55-6d715565eefd

**Expected Result:**
http://bsa-talents.us-east-1.elasticbeanstalk.com/api/v1/user-details/{userId}
**Visual Proof (screenshots, videos, text):**

**Severity:**
Critical (S2)

![url](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/7a1f54b0-ecac-4902-a25b-2d28aed7bc19)
equest URL

**Comment by savinaDaria** [comment]
was fixed in [this PR](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/pull/494)
