### ISSUE TITLE
Connect Verification label to API

### ISSUE THREAD

**Issue by lavandosya** [BinaryStudioAcademy/bsa-2023-bsa-talents#580]
We need to connect with the userDetails store for employers and talents after pressing the "publish now" button after the preview page. 

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/116720360/7339c3ee-fd44-49c8-bd42-bf29869b4ef5)

**Comment by anna9314** [comment]
Tested
