### ISSUE TITLE
[BUG] The layout of the Candidate's page is not matched with design

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#585]
**Description:**
The layout of the Candidate's page does not match with design

**Preconditions:**
The BSA talent website is open

**Environment:**
OS Windows 11
Google Chrome 116.0

**Steps to reproduce:**
1. Sign up as an employer
2. Go to the  Candidate's page
3. Pay attention to the layout of the Candidate's page

**Actual Result:**
The Candidate's page is shifted to the left

**Expected Result:**
The Candidate's page is aligned as per design

**Visual Proof (screenshots, videos, text):**
![Screenshot_1](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/d847ddbb-701c-45d8-bd44-f50a92b3374d)

**Severity:**
Minor (S4)

**Comment by ed9ward** [comment]
Tested
