### ISSUE TITLE
[BUG] The layout of the Candidate's preview page is displayed broken

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#592]
**Description:**
The layout of the Candidate's preview page is displayed broken

**Preconditions:**
The BSA talent website is open

**Environment:**
OS Windows 11
Google Chrome 116.0

**Steps to reproduce:**
1. Sign up as a talent
2. Fill in all steps
3. Go to the Candidate's preview page
4. Pay attention to the layout of the Candidate's preview page

**Actual Result:**
The layout of the Candidate's preview page is displayed broken
![image (13)](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/90cf9431-a11c-42cc-aa40-5852f4b9ebd0)

**Expected Result:**
Layout is displayed according to the design
![Screenshot_3](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/288f8352-0516-4dfe-bd9f-a3e7c2305e77)

**Severity:**
Major (S3)

**Comment by ed9ward** [comment]
Tested
