### ISSUE TITLE
Make changes to the code according to B20, B22, and B23 rules in quality criteria

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2023-bsa-talents#599]
Go through the whole project and fix these and similar issues

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/105710998/d03c606a-307a-4d51-89ab-91ef3c4f1c7d)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/105710998/50dc87c8-a39a-4432-b424-468c1f7ef5a1)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/105710998/720c423f-40c2-404a-a93e-cbc1c978d89c)

**Comment by nika-sirak** [comment]
- [x] B20
- [x] B22
- [x] B23
- [x] A3
