### ISSUE TITLE
Create a Chip component which we will use for badges

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2023-bsa-talents#6]
![Image](https://user-images.githubusercontent.com/105710998/261579565-a866c939-5652-4ee5-8f70-76f834240a8a.png)

![Image](https://user-images.githubusercontent.com/105710998/261579649-1bd8ed45-0f43-4b83-b9eb-c424c407ebc1.png)

![Image](https://user-images.githubusercontent.com/105710998/261579689-28faa55f-0338-4ceb-92f9-08a459c91a6d.png)

**Comment by nikita-remeslov** [comment]
@anton-otroshchenko this is chips - https://mui.com/material-ui/react-chip/

**Comment by anton-otroshchenko** [comment]
Info: https://mui.com/material-ui/react-chip/
