### ISSUE TITLE
Make changes to the code according to B34 and B38 rules

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2023-bsa-talents#601]
Go through the whole project and fix these and similar issues

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/105710998/f3cbec9a-d2be-428b-a616-9d876cae6351)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/105710998/785a5813-bc34-469c-b90a-64ac2f2d7956)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/105710998/24b28768-2526-4b16-800c-b0a2251619b6)

**Comment by nika-sirak** [comment]
- [x] B34
- [x] B38
