### ISSUE TITLE
Make changes according to A3, A10 and A11 rules

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2023-bsa-talents#603]
Go through the whole project and fix these and similar issues

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/105710998/62af7040-0483-457b-8899-704ae655d456)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/105710998/bce37988-51d9-4527-8674-5521c5ed1940)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/105710998/ad33ba1d-4f55-428e-89e9-9e2882a4c75d)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/105710998/ae614a66-088b-4b41-bff2-4ad7f3715eca)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/105710998/1662a2a7-d0f5-4e56-bddb-b79766ddb926)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/105710998/6ab318bc-b3f2-4888-aa5a-2ead7155a740)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/105710998/f0edaa52-7688-4db4-9284-86889d477d45)

**Comment by lavandosya** [comment]
I guess BSACharacteristics it's just mock data for now, no need to move to shared folder
