### ISSUE TITLE
Connect closed candidate page

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#614]
On the page http://bsa-talents.us-east-1.elasticbeanstalk.com/candidates/44

Look on Figma something like "Candadate's page closed info"
https://www.figma.com/file/Yd7USgP7PLvA0W794jHXWu/BSA_recruting?type=design&node-id=4854-990&mode=design&t=OXVUvpPnPy1nAdr2-4

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/4421446f-b9dd-4955-8f1a-c24e2fcc21a3)

**Comment by ed9ward** [comment]
Tested
