### ISSUE TITLE
Add a placeholder for the profile photo and company logo on the Employer’s onboarding page

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#619]
Use these as a placeholder. Color should be suited to the design
https://fontawesome.com/icons/image?f=classic&s=solid
https://fontawesome.com/v5/icons/user-circle?f=classic&s=solid&pc=%23335a9e 

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/e74468ce-c6cf-4865-ab66-464e8c6b72b5)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/12197409-a6d6-4fec-8b39-8fdd397088bb)

**Comment by ed9ward** [comment]
Tested
