### ISSUE TITLE
[BUG] The site crash appears after clicking on the site logo on the Employer's onboarding page

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#623]
**Description:**
The site crash appears after clicking on the site logo on the Employer's onboarding page

**Preconditions:**
open http://bsa-talents.us-east-1.elasticbeanstalk.com/sign-up
type valid data
choose radiobutton "I am hiring"

**Environment:**
OS - Windows
Browser - Google Chrome
Version - 116.0.5845.142

**Steps to reproduce:**

1. Fill in all fields
2. Press the button "Submit for verification"
3. After the redirection on the page “Your profile” click on the site logo in the header click on the site logo in the header
4. Pay attention to the error that appears

**Actual Result:**
The site crash appears after clicking on the site logo in the header  on the Employer's onboarding page

**Expected Result:**
The user who chooses "I am hiring" is redirected from the Employer’s onboarding page to the page Sign In after the clicking on site logo in the header

**Visual Proof (screenshots, videos, text):**
https://drive.google.com/file/d/1nQFdvu-lINieCQhhipldaCZQIve_FN8f/view?usp=sharing

**Severity:**
Blocker (S1)

**Comment by savinaDaria** [comment]
First fix [this bug](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/617)
This should then dissappear

**Comment by JosuerBague** [comment]
Tested this in development. No crash.
