### ISSUE TITLE
[BUG] Mobile Step 2 Badges typo

### ISSUE THREAD

**Issue by ed9ward** [BinaryStudioAcademy/bsa-2023-bsa-talents#635]
**Description:**

**Environment:**
Win 11, Chrome 117

**Steps to reproduce:**
1. Go to Step 2

**Actual Result:**
Typo, extra " symbol in the second badge name at the end

**Expected Result:**
It shouldn't be there

**Visual Proof (screenshots, videos, text):**

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/7b93b6ba-46e6-4390-a1bf-7ffc0ab48c83)

**Severity:**
Minor

**Comment by mskmee** [comment]
we wouldnt have thoose values after https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/pull/569
will accepted
