### ISSUE TITLE
Company talent hiring info

### ISSUE THREAD

**Issue by MaksymGavatuk** [BinaryStudioAcademy/bsa-2023-bsa-talents#638]
We need implement logic to hiring info.

Backend:
- [x] create relation table with companyId => userDetailsTable, talentId => userDetailsTable and other columns which we provide while hiring
- [x] create repository with create method and method to get all records about hiring
- [x] create service with such method
- [x] create endpoint GET and POST

Frontend:
- [x] implement hiring process (talent, company)
- [x] add list of hiring record in admin layout (Maybe add another page for this) - https://mui.com/material-ui/react-table/

Screenshots: 
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/93519384/84a1c651-6cc4-4ea4-a028-b194f7d54885)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/93519384/4aff67a3-477a-4cea-8815-6e2487b391ff)

**Please clarify hiring process with QA team !!!**

**Comment by MaksymGavatuk** [comment]
**Please clarify hiring process with QA team !!!**

**Comment by anna9314** [comment]
tested
