### ISSUE TITLE
[BUG] Mobile see password icon shifted after hint appears

### ISSUE THREAD

**Issue by ed9ward** [BinaryStudioAcademy/bsa-2023-bsa-talents#639]
**Description:**

**Environment:**
Win 11, Chrome 117

**Steps to reproduce:**
1. Go ti Login and press Submit

**Actual Result:**
Icon shifter outside

**Expected Result:**
Icon always inside the field

**Visual Proof (screenshots, videos, text):**

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/62cfa5dc-67ab-43df-be87-54ab976e4eee)

**Severity:**

**Comment by illia-dobro** [comment]
I resolved the bug in bt-531: Added Employer Profile screen, that has already been merged 

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/112649713/9ca04c85-9f2f-47d1-a934-01835ea02205)

**Comment by anna9314** [comment]
Tested
