### ISSUE TITLE
Change a placeholder for the profile photo and company logo on the Employer’s onboarding page

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#640]
Use these as a placeholder. Color should be suited to the design
https://fontawesome.com/icons/image?f=classic&s=solid
https://fontawesome.com/v5/icons/user-circle?f=classic&s=solid&pc=%23335a9e

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/87e34484-51d0-446f-bf58-bc615144e8b9)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/7649a90b-bc2e-4fd6-997e-fcb5e3550316)

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695631719788729

**Comment by anna9314** [comment]
Tested
