### ISSUE TITLE
Add placeholder for Talent profile photo on step 04/talent profile

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#641]
Use this as a placeholder. Color should be suited to the design
https://fontawesome.com/v5/icons/user-circle?f=classic&s=solid&pc=%23335a9e

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/573186f8-8e53-4c76-8b1e-7402686b6167)

**Comment by Oleksandrra** [comment]
tested

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/109c2cbf-856b-47f2-bf04-5884c46b5486)
