### ISSUE TITLE
[BUG] Fix Talent onboarding navigation on app launch

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#642]
Steps to reproduce:
1. As a new user fill step 1
2. Click next
3. Kill the app
4. Relaunch the app

Actual Result:
User is again on step 1, also there is no loader or overlay view on data loading 

Expected Result:
User should appear on the last available step (step 2 for this example), 
While user data loading user sees a loader or overlay view (loader will be better)

Visual Proof (screenshots, videos, text):

https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/103518438/2065ff74-c52a-479a-8073-449cb990eadf

**Comment by anna9314** [comment]
Tested
