### ISSUE TITLE
Add placeholder for Talent profile photo on step 04/talent profile

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#643]
Use this as a placeholder. Color should be suited to the design
https://fontawesome.com/v5/icons/user-circle?f=classic&s=solid&pc=%23335a9e

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/65ec650e-259b-40a5-9b00-062a62670612)

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695631719788729

**Comment by anna9314** [comment]
Tested
