### ISSUE TITLE
Add a placeholder for the profile photo and company logo on the Employer’s onboarding page

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#644]
Use these as a placeholder. Color should be suited to the design
https://fontawesome.com/icons/image?f=classic&s=solid
https://fontawesome.com/v5/icons/user-circle?f=classic&s=solid&pc=%23335a9e

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/5ce63c30-04cd-4b72-b2c2-61264f5ede4b)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/6937af4e-499b-4c90-9adf-c5d849a4cf8a)

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695631719788729

**Comment by anna9314** [comment]
Tested
