### ISSUE TITLE
Replace mocked badges with real data

### ISSUE THREAD

**Issue by vladjsp** [BinaryStudioAcademy/bsa-2023-bsa-talents#662]
**Acceptance criteria:**

We should connect the client to API

- Talent should be able to select badges “Communication score”, “Working with the team score”. “Project score”, “Lecture score”, “Level of English” should be displayed by default.
- All badges should display the score.
- When talent switches between steps, chosen badges should be saved.
- Chosen badges should be displayed on the Talent card/profile

**Comment by anna9314** [comment]
Tested
