### ISSUE TITLE
Replace mocked hard skills with real data for onboarding and profile

### ISSUE THREAD

**Issue by vladjsp** [BinaryStudioAcademy/bsa-2023-bsa-talents#663]
We should connect the client to API

**Acceptance criteria:**

-  When talent switches between onboarding steps, chosen the hard skills should be saved
- Chosen hard skills should be displayed on the Talent card/profile

**Comment by nikita-remeslov** [comment]
Link PR

UPDATE: I was looking in the wrong place!

**Comment by nika-sirak** [comment]
Is it still in progress?

**Comment by ed9ward** [comment]
Tested
