### ISSUE TITLE
Connect chat to API

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#664]

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695810342361249

**Comment by Oleksandrra** [comment]
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/50ffdf07-0d57-41f6-8d76-134834202d03)

tested

**Comment by Oleksandrra** [comment]
@anogire @likeri29 

If I use dark mode, the color of text is white
