### ISSUE TITLE
Add logic to the "Save without publishing" / "Publish now" button when the user Signs up

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#667]
**Acceptance criteria:**

- When a user fills in all steps and clicks on "Publish now" he stays on the Preview page and has the possibility to go to the Profile page to edit 
- When a user fills in all steps and clicks on "Save without publishing" he is redirected to the Profile page where can edit info and click on the "Publish" button (will be added to the profile)
- When a user clicks on the "Publish" button on the Profile page he is redirected to the Preview page

**Comment by nika-sirak** [comment]
It is related to #675 and #631

**Comment by savinaDaria** [comment]
Added Home component in PR

**Comment by nika-sirak** [comment]
- [x] When a user fills in all steps and clicks on "Publish now" he stays on the Preview page and has the possibility to go to the Profile page to edit
- [x] When a user fills in all steps and clicks on "Save without publishing" he is redirected to the Profile page where can edit info and click on the "Publish" button (will be added to the profile)
- [x] When a user clicks on the "Publish" button on the Profile page he is redirected to the Preview page

**Comment by Oleksandrra** [comment]
tested
