### ISSUE TITLE
Add logic to the "Save without publishing" / "Publish now" button when the user Signs up

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#668]
**Acceptance criteria:**

- When a user fills in all steps and clicks on "Publish now" he stays on the Preview page and has the possibility to go to the Profile page to edit
- When a user fills in all steps and clicks on "Save without publishing" he is redirected to the Profile page where can edit info and click on the "Publish" button (will be added to the profile)
- When a user clicks on the "Publish" button on the Profile page he is redirected to the Preview page

**Comment by likeri29** [comment]
Preview page, you mean preview screen in the talent onboarding?

**Comment by anna9314** [comment]
Yes, preview screen in the talent onboarding. It's step 5

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695898482546199
