### ISSUE TITLE
Change preview project mock data to real data

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#674]
**Acceptance criteria:**

- When talent adds a link to the repo (github) on the onboarding flow it should display [a github preview placeholder](https://www.npmjs.com/package/@dhaiwat10/react-link-preview) on the Preview page
- When talent adds a link to the repo (github) on the onboarding flow there should be displayed the project description and project name (remove the weeks and team composition) on the Preview page
- The project description and project name should be pulled from the LMS
- When the user clicks on the "Repository link" button he is redirected to the repo

on the 1st screen is an example of how it will be returned from the LMS
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/64196a03-466a-495c-9e15-0c15c7ec87f9)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/446728c2-925e-4fe5-b690-11e0c33bae5d)

**Comment by ed9ward** [comment]
Tested
