### ISSUE TITLE
Change preview project mock data to real data

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#677]
**Acceptance criteria:**

- When talent adds a link to the repo (github) on the onboarding flow it should be displayed a github preview placeholder on the Preview page
- When talent adds a link to the repo (github) on the onboarding flow there should be displayed the project description and project name (remove the weeks and team composition) on the Preview page
- The project description and project name should be pulled from the LMS
- When a user clicks on the "Project" he should be redirected to the repo (the browser open)

on the 1st screen is an example of how it will be returned from the LMS
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/64196a03-466a-495c-9e15-0c15c7ec87f9)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/43398aab-cf57-4493-8e53-c0488b2c3f1a)

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695898482546199

**Comment by ed9ward** [comment]
Tested
