### ISSUE TITLE
[BUG] "Your average project score" checkbox is not displayed as selected by default

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#678]
**Description:**
"Your average project score" checkbox is not displayed as selected by default

**Preconditions:**
The BSA talent website is open

**Environment:**
OS Windows 11
Google Chrome 116.0

**Steps to reproduce:**
1. Sign up as a talent
2. Go to step 02
3. Pay attention to the Your average project score" checkbox

**Actual Result:**
"Your average project score" checkbox is not displayed as selected by default

**Expected Result:**
"Your average project score" checkbox must be displayed as selected by default

**Visual Proof (screenshots, videos, text):**
![Screenshot_8](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/eef96140-3aa9-4ce0-89be-a9c6a91c12f3)

**Severity:**
Minor (S4)

**Comment by JosuerBague** [comment]
Addressed in #662

**Comment by anna9314** [comment]
tested
