### ISSUE TITLE
Change mock data on Chats screen to real data

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#680]
**Acceptance criteria:**

- Profile name (Junior Java Developer) should be displayed for the employer on the Chats screen (before the candidate shared contacts) - screen 1
- Full name should be displayed for the employer on the Chats screen (after candidate shared contacts) - screen 1
- Info block on the right side should be displayed with real data that the employer fills in on the onboarding (company name, full name, position, description, website)
- For talent on the Chats screen should be displayed Company name - screen 2
- Employer can go to the Closed candidate's page by clicking on the Profile name on the Chats screen
- Employer can go to the Open candidate's page by clicking on the Full name on the Chats screen
- Talent can go to the Employer card by clicking on the company logo or name on the Chats screen

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/847ae89a-a897-48bd-bbd9-3b0babc82275)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/63d3394a-c91c-4d6b-b955-f20430f24bd2)

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695810342361249

**Comment by ed9ward** [comment]
Tested
