### ISSUE TITLE
[BUG] Full name field displays the profile name on the onboarding flow

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#688]
**Description:**
Full name field displays the profile name on the onboarding flow when filling in steps 1-4 and go to step 4

**Preconditions:**
The BSA talent app is open

**Environment:**
Android 13
Samsung Galaxy A52 (2340x1080)

**Steps to reproduce:**
1. Sign up as a talent
2. Fill out steps 1-3
3. Go to step 4
4. Pay attention to the Full name field

**Actual Result:**
When a user fills in steps 1-3 and goes to step 4 the Full name field displays the already profile name (which was entered in step 1)

**Expected Result:**
When a user fills in steps 1-3 and goes to step 4 the Full name field displays a user name (should be pulled from LMS) 

**Visual Proof (screenshots, videos, text):**
![Screenshot_16](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/fa960ef8-8e63-47e3-ad62-835f9026d297)
![Screenshot_17](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/e58000d9-c934-4195-8c15-e7882855fb1f)

**Severity:**
Major (S3)

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695824001443929

**Comment by anna9314** [comment]
Tested
