### ISSUE TITLE
[BUG] Job title is displayed on the Preview page instead of the Profile name

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#689]
**Description:**
Job title is displayed on the Preview page instead of the Profile name

**Preconditions:**
The BSA talent app is open

**Environment:**
Android 13
Samsung Galaxy A52 (2340x1080)

**Steps to reproduce:**
1. Sign up as a talent
2. Fill out all steps
3. Go to the Preview page
4. Pay attention to the Profile name

**Actual Result:**
Job title is displayed on the Preview page instead of the Profile name

**Expected Result:**
 Profile name is displayed on the Preview page 
 
**Visual Proof (screenshots, videos, text):**
![Screenshot_18](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/ed2c7330-ef56-47b8-8acb-ee6164ea69e0)
![Screenshot_19](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/0e5563fb-3f81-4654-b09a-73ce4c04e28b)

**Severity:**
Minor (S4)

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by anogire** [comment]
should be also fixed because of [PR](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/pull/748)

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695824001443929

**Comment by anna9314** [comment]
Tested
