### ISSUE TITLE
Make changes in search-users endpoints

### ISSUE THREAD

**Issue by MChornomaz** [BinaryStudioAcademy/bsa-2023-bsa-talents#690]
-  Add search_type column to user-details table in DB
 -  add badges and hardskills to the response
 -  show only candidate, which were approved by admin
 -  change code in repository accorditng to task #605 
 -  change sorting by date from sorting by creation date to sorting by publish date

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/68593365/35d69b5c-f892-464c-a03c-6c67cff5b5c3)

**Comment by anna9314** [comment]
Tested
