### ISSUE TITLE
Validate talent email does it exist on LMS

### ISSUE THREAD

**Issue by JemiJe** [BinaryStudioAcademy/bsa-2023-bsa-talents#691]
prevent to sign up if user typed email which doesn't exist on LMS

When a user enters an email that doesn't exist on LMS and clicks sign up the error message "Please, use your LMS email" (or something like this) should be displayed

**Comment by JemiJe** [comment]
message will be 'User Not Found: To sign up, please use the same email address you used when registering with Binary Studio Academy' on yellow color of warning

**Comment by ed9ward** [comment]
Tested
