### ISSUE TITLE
[BUG] Profile photo is placed lower than a company logo 

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#694]
**Description:**
Profile photo is placed lower than a company logo on the Employer onboarding page

**Preconditions:**
The BSA talent app is open

**Environment:**
Android 13
Samsung Galaxy A52 (2340x1080)

**Steps to reproduce:**
1. Sign up as an employer
2. Pay attention to the Profile photo and Company logo fields

**Actual Result:**
Profile photo is placed lower than a company logo 

**Expected Result:**
Profile photo and Company logo fields are aligned

**Visual Proof (screenshots, videos, text):**
![Screenshot_1](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/94a32961-96b5-4de0-b9c4-1998eac91713)

**Severity:**
Minor (S4)

**Comment by anna9314** [comment]
The same for my profile page

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/60cb6382-9de6-4ec3-9d38-6976a38d5488)

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695824001443929

**Comment by anna9314** [comment]
Tested
https://prnt.sc/hc4JZ795ruCV
