### ISSUE TITLE
update Connect Chat to API

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#698]
1.After clicking on the title of “Profile name” before Talent share contact, the Employer is redirected to Candidate's closed card
2.After Talent sharing CV and contact with the Employer , the Employer  receive message “Talent has  shared contacts”
3.After clicking on the title of “Profile name” after Talent share contact, the Employer is redirected to Candidate's open card

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/61b50087-4ec5-44cf-b863-fc2be50d370f)

**Comment by ed9ward** [comment]
Tested
