### ISSUE TITLE
Create talent/company contact sharing

### ISSUE THREAD

**Issue by savinaDaria** [BinaryStudioAcademy/bsa-2023-bsa-talents#702]
To connect Open(Shared) candidate page we need to create separate table with talent/company interactions(connections)- action when talent shares info with company.

**Structure:**
id (uuid)
talent_id (uuid)
company_id (uuid)

**Methods:**
GET /?talentId&companyId
POST 

+ Add stores on frontend for sharing contacts and for getting info that talent shared info with company

**Comment by ed9ward** [comment]
Tested
