### ISSUE TITLE
Disable link to my profile until onboarding finished talent/employer

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#704]
- When a talent fills in all steps and clicks on "Publish now" he stays on the Preview page and has the possibility to go to the Profile page to edit
- When the employer fills in all info and clicks on "Submit for verification"  he stays on the same page and has the possibility to go to the Employer page to edit
- Before finishing onboarding link should be disabled

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/e09acd09-50a9-4781-a5ce-12ff71810368)

**Comment by anna9314** [comment]
it can be connected with these ticket
[Add logic to Sign in flow when the profile is saved in drafts/published/approved by admin#670](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/670)

[Add logic Sign in/Sign up Employer#712](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/712)

**Comment by nika-sirak** [comment]
While the user is on the onboarding process My profile button is disabled.  Only on the last step preview on talent onboarding process the button will be able.

**Comment by ed9ward** [comment]
Tested
