### ISSUE TITLE
Create get current user endpoint

### ISSUE THREAD

**Issue by MaksymGavatuk** [BinaryStudioAcademy/bsa-2023-bsa-talents#71]
Implement endpoint for get current user
When user refresh page or close it and after open we need to get token from localStorage and call getCurrentUser endpoint to load current user.

- [x] userRepository (Server)
- [x] add endpoint (Server)
- [x] add user to store (Client)
- [x] load user when page loaded (Client)

**Comment by anna9314** [comment]
Tested
Swagger does not attach a token. 
In Swagger status code is 500
In Postman status code is 200

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/5c54679a-b936-4090-a361-d62b0cf68a02)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/f0e0d3e1-df63-410a-b579-64aa2c9b6770)
