### ISSUE TITLE
Add logic Sign in/Sign up Employer

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#712]
- When the employer signs up, fills in all fields, and clicks on the "Submit for verification" button, he is redirected to the profile page and a verification label is rendered.
- When the employer click Save draft he is redirected to the profile where there is the "Submit for verification" button and he can submit the profile from the Profile page. After he click "Submit for verification" button a verification label is rendered.
- When the employer clicks submit and signs in but the admin hasn't approved the yet profile he is redirected to the Profile page
- When the employer signs in and admin approved profile  he is redirected to the Search page

**Rename the Preview to Save draft (Employer onboarding)**

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/c8d60071-3fad-4c6b-bd63-974e0183f22b)

**Comment by anna9314** [comment]
Connected ticket

[Disable link to my profile until onboarding finished talent/employer#704](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/704)

**Comment by nika-sirak** [comment]
When the employer clicks submit and signs in but the admin hasn't approved the yet profile he is redirected to the Profile page - is fixed in https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/pull/805

**Comment by ed9ward** [comment]
Approved Emp goes to Profile still, not search

**Comment by ed9ward** [comment]
Approved Talent goes to Preview too
