### ISSUE TITLE
Add logic Sign in/Sign up Employer

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#714]
- When the employer signs up, fills in all fields, and clicks on the "Submit for verification" button, he stays on this page (can go to the profile) and the "Submit for verification" should be removed.
- When the employer clicks on the "Submit for verification" button profile link is able
- Before submitting a profile employer can not go to the profile page
- When the employer didn't submit the profile then signs in he is redirected to the profile where there is the "Submit for verification" button and he can submit the profile from the Profile page
- When the employer clicks submit and signs in but the admin hasn't approved the yet profile he is redirected to the Profile page
- When the employer signs in and admin approved profile he is redirected to the Search page

**Comment by anna9314** [comment]
**Rename the Preview to Save draft (Employer onboarding)**



![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/c8d60071-3fad-4c6b-bd63-974e0183f22b)

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695824001443929

**Comment by anna9314** [comment]
Tested
