### ISSUE TITLE
[MOBILE] Change requirements to the fields for typing link

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#724]
You can see the requirements in the ticket https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/723

**Comment by illia-dobro** [comment]
It has already been changed in the shared folder It has to work and for mobile devices.

**Comment by mskmee** [comment]
@illia-dobro if you check and it works, then move ticked to test please, assigning you self before

**Comment by Oleksandrra** [comment]
tested
