### ISSUE TITLE
[BUG]The sidebar on the page "Search" is not displayed when using 100% screen size

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#728]
**Description:**
The sidebar on the page "Search" is not displayed when using 100% screen size

**Preconditions:**
open http://bsa-talents.us-east-1.elasticbeanstalk.com/
login as Employer with valid data
open page http://bsa-talents.us-east-1.elasticbeanstalk.com/candidates

**Environment:**
OS - Windows
Browser - Google Chrome
Version - 116.0.5845.142

**Steps to reproduce:**

1. Zoom out page size to 67%
2. Pay attention that the search page is fully displayed, including the sidebar
3. Zoom in page size to 100%, start typing text in the search field
4. Pay attention that the sidebar with filters is displayed after placing the cursor in the search query input field

**Actual Result:**

1. The sidebar on the page "Search" is not displayed when using 100% screen size
2. The sidebar with filters is displayed after placing the cursor in the search query input field

**Expected Result:**

1. The search page is fully displayed, including the sidebar with filters
2. The sidebar has a fixed position

**Severity:**
Blocker (S1)

**Visual Proof (screenshots, videos, text):**
https://drive.google.com/file/d/1Nr_NsEiIXtnMdIwJeMmvxOdYloIN_9Ky/view?usp=drive_link

**Comment by vladjsp** [comment]
not relevant. works as expected
