### ISSUE TITLE
[BUG] Logout button is cut off on the Employer profile page

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#729]
**Description:**
Logout button is cut off on the Employer profile page

**Preconditions:**
The BSA talent app is open

**Environment:**
Android 13
Samsung Galaxy A52 (2340x1080)

**Steps to reproduce:**
1. Sign up as an employer
2. Fill in onboarding
3. Click on the "Submit for verification" button
4. Pay attention to the Logout button

**Actual Result:**
Logout button is cut off on the Employer profile page

**Expected Result:**
Logout button is displayed fully visible

**Visual Proof (screenshots, videos, text):**
![Screenshot_13](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/752f9b8d-187e-4821-a471-192b2d9f5cc5)

**Severity:**
Minor (S4)

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by anna9314** [comment]
The same bug for talent profile(
[[BUG] Logout button is cut off on the Talent profile page#753](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/753)

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695824001443929

**Comment by anna9314** [comment]
Tested
