### ISSUE TITLE
[BUG] The Employer can see Talant`s full name in search result

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#730]
**Description:**
As a result of  the search returned the Talent’s cards, which contain Talant`s page opened info

**Preconditions:**
open mobile app
sign in as an employer

**Environment:**
OS - Android
Version - 12 SP1A.210812.016

**Steps to reproduce:**

1. open the search page
2. pay attention that as a result of the search returned the Talent’s cards, which contain Talant`s page opened info - Talant’s full name

**Actual Result:**
1. As a result of  the search returned the Talent’s cards, which contain Talant`s page opened info - Talant’s full name

**Expected Result:**
1. As a result of  the search returned the Talent’s cards, which contain Talant`s page closed info

**Visual Proof (screenshots, videos, text):**

**Severity:**
Critical (S2)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/a6fc4fca-b891-49d1-b9a4-a55070f1fff2)

**Comment by mskmee** [comment]
@Oleksandrra  PO said that we need it on the last presentation

**Comment by Oleksandrra** [comment]
@mskmee I think we need "Profile name", not "Full name"

**Comment by mskmee** [comment]
@mskmee profile name could be like a nick name or just abz....dwaW, are you sure about it? Quess it's better to clarify it with PO. Can you ask about it, please

**Comment by Oleksandrra** [comment]
@mskmee 
https://www.figma.com/file/Yd7USgP7PLvA0W794jHXWu/BSA_recruting?type=design&node-id=4854-990&mode=design&t=bG9PQ3JqOHMRESt2-4

before Talent shares CV and contact, the Employer can not see personal data

**Comment by mskmee** [comment]
@Oleksandrra  I'll remove thoose data at all, because profile name can be like real name

**Comment by Oleksandrra** [comment]
@mskmee 
Can you check, please, in this case, is the real full name specified in the profile name? or it is the full name that is shown
if the talent specifies the full name in the profile name, the admin will have a reason to reject the approval of such an account

**Comment by mskmee** [comment]
@Oleksandrra  profile names and full names are different values. Don't know if it a good idea to shows candidates profile names. But if you will say so, I'll do it :)

**Comment by Oleksandrra** [comment]
@mskmee Yes, profile name can be super dev or abracadabra, but at the same time Admin checks all typed data

**Comment by mskmee** [comment]
@Oleksandrra Okey, than it's gonna be admin responsobility :)

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695803236230149

**Comment by Oleksandrra** [comment]
tested
