### ISSUE TITLE
Remove mocked data from chat user details screen with real data

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#740]
**This screen should be opened in user clicks on user info in chat header.** This screen should be different for talent and for employer ( I have screen only for talent, see web to know how it should look for employer)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/103518438/1a05ea79-5f05-4737-b014-f4ab324088bf)

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695886214948429

**Comment by anna9314** [comment]
tested
