### ISSUE TITLE
Add placeholder “There are no active conversations yet When employers want to contact you, all chats will be here” on the page "Chat" before receiving the first message from an employer

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#743]
You can see screen https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/742

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695824001443929

**Comment by Oleksandrra** [comment]
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/dd9b166a-611e-47a2-ab19-abdf35985fb6)

tested
