### ISSUE TITLE
[BUG] The second letter of the abbreviation is displayed from lower case on the search page

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#755]
**Description:**
 The second letter of the abbreviation is displayed from lower case on the search page

**Preconditions:**

**Environment:**
OS
Browser
Version

**Steps to reproduce:**
1. Sign in as an employer
2. Go to the Search page
3. Pay attention to the Profile name and Job Title

**Actual Result:**
Profile name was entered like QA but the second letter of the abbreviation is displayed in lowercase on the search page
 
**Expected Result:**
The abbreviation is displayed in upper case on the search page 

**Visual Proof (screenshots, videos, text):**
Was entered
![Screenshot_6](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/41671f50-eebf-4f0d-b4ee-edbdabd6e713)
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/17d46021-9cbc-4c5d-b60f-f81d3663c876)

what is displayed
![Screenshot_4](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/e41abb29-2df6-4fc4-ac06-b21b70afcf47)
![Screenshot_5](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/df1e0323-dd21-4939-9ee9-498aa47d9b23)

**Severity:**
Minor (S4)

**Comment by Oleksandrra** [comment]
tested, the same
build (27.09 17:13)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/65db60bd-72af-41df-ae2f-8e7118e7549f)

**Comment by anogire** [comment]
Build hasn't updated yet

**Comment by anna9314** [comment]
Tested
