### ISSUE TITLE
[BUG]The placeholder with validation error message about no access to page Chat appears under another placeholder on page “Profile”

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#768]
**Description:**
The placeholder with a validation error message about no access to page Chat appears under another placeholder on page “Profile”

**Preconditions:**
- open http://bsa-talents.us-east-1.elasticbeanstalk.com/
- login as Talant with valid data
- filled in the required data in the registration steps

**Environment:**
OS - Windows
Browser - Mozilla Firefox
Version - 117.0.1

**Steps to reproduce:**
1. Click the button “Save without publishing”
2. After redirecting to the page “Profile” click on the icon “Chat”
3. Pay attention to the placement validation error message about no access to page Chat

**Actual Result:**
The placeholder with a validation error message about no access to page Chat appears under another placeholder on page “Profile”

**Expected Result:**

1. The placement of elements corresponds to the design
2. No element overlaps each other

**Severity:**
Minor (S4)

**Visual Proof (screenshots, videos, text):**
![not acc](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/140751314/8da6716c-69f9-4aef-aeb0-88b7208ee235)

**Comment by ed9ward** [comment]
Tested
