### ISSUE TITLE
[BUG] Skills and Projects tab is displayed stretched when too many skills are added

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#774]
**Description:**
Skills and Projects tab is displayed stretched when too many skills are added on the Talent profile

**Preconditions:**

**Environment:**
OS Windows 11
Google Chrome 116.0

**Steps to reproduce:**
1. Sign up 

**Actual Result:**
Skills and Projects tab is displayed stretched when too many skills are added on the Talent profile

**Expected Result:**
Skills and Projects tab is displayed like on Step 03

**Visual Proof (screenshots, videos, text):**
![Screenshot_12](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/3dc7f42a-65bf-4f77-96a7-85cf2ed093e7)

**Severity:**
Minor (S4)

**Comment by ed9ward** [comment]
Tested
