### ISSUE TITLE
[BUG] Description and preview of the repo are not displayed on the Preview page

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#785]
the repo link was added but description and preview of the repo are not displayed on the Preview page
![Screenshot_17](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/e814cf40-cce1-400c-96fc-fc4afc653b01)

**Comment by Monyster** [comment]
We get repo link from lms.
This was done in another :
- task #674 
- PR #741

**Comment by ed9ward** [comment]
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/3554c451-553f-41a1-8e47-9d1d7bdaddd2)
