### ISSUE TITLE
[BUG] "Waiting for approval" doesn't disappear/change when user is approved (using db)

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#791]
**Description:**
"Waiting for approval" doesn't disappear/change when the user is approved (using db)

**Expected Result:**
"Waiting for approval" disappears/changes when the user is approved (using db)
After approve user is displayed on the search page

**Visual Proof (screenshots, videos, text):**
![Screenshot_22](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/048f8f6b-969c-497e-b44b-ac688088052e)
![Screenshot_24](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/c19a1587-f9bf-4f36-b134-7862c45a8010)

**Severity:**
Major (S3)

**Comment by anna9314** [comment]
think it also should be removed when the user is approved
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/ae24268f-d427-420b-bb66-aa20bae7db21)

**Comment by ed9ward** [comment]
Tested
