### ISSUE TITLE
[BUG] Talent's photo and CV aren't saved after uploading

### ISSUE THREAD

**Issue by Oleksandrra** [BinaryStudioAcademy/bsa-2023-bsa-talents#793]
**Description:**
Talent's photo and CV aren't saved after uploading on the page "Profile". Button "Save" does not become active, only "Publish now"

**Expected Result:**
The Talent's photo is saved and displayed

**Visual Proof (screenshots, videos, text):**
https://drive.google.com/file/d/1kblYzWelHQekQDFDGnEtlihlOD7OTVZK/view?usp=drive_link

**Comment by ed9ward** [comment]
Still got this, file size is ok


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/39ee8384-1717-4931-8b21-1e00813b035b)


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/8355821/e4772f63-b0bb-42ac-ad7b-c4d708d66ca1)
