### ISSUE TITLE
[BUG] Employer can not go to the Chats when he is approved

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#798]
**Description:**
Employer can not go to the Chats when he is approved. Notification is displayed

**Expected Result:**
After approval employer can go to the Chats

**Visual Proof (screenshots, videos, text):**
![Screenshot_27](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/e115c78b-127d-48ee-a8f8-43666d97b202)

**Severity:**
Critical (S2)

**Comment by JemiJe** [comment]
was fixed before

**Comment by ed9ward** [comment]
Tested
