### ISSUE TITLE
[BUG] Error message is displayed after updating Employer profile

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#799]
**Description:**
Error message is displayed after updating the Employer profile

**Expected Result:**
Just a success message is displayed when updating the profile

**Visual Proof (screenshots, videos, text):**
![Screenshot_26](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/0a752d94-c43f-42ed-9c19-b927d480b983)

**Severity:**
Major (S3)

**Comment by ed9ward** [comment]
Tested
