### ISSUE TITLE
[BUG] Error message is displayed after going to step 03

### ISSUE THREAD

**Issue by anna9314** [BinaryStudioAcademy/bsa-2023-bsa-talents#806]
**Description:**
Error message is displayed after going to step 03

**Actual Result:**
When filling in step 2 
click on the next button 
Error message is displayed after going to step 03

**Expected Result:**
Error message is not displayed after going to step 03

**Visual Proof (screenshots, videos, text):**
![Screenshot_29](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/97385ad1-49cd-4f7e-8808-c14a419d2f1e)

**Severity:**
Major (S3)

**Comment by savinaDaria** [comment]
check if this bug dissappears in #662

**Comment by anna9314** [comment]
tested
