### ISSUE TITLE
Sign-up

### ISSUE THREAD

**Issue by MaksymGavatuk** [BinaryStudioAcademy/bsa-2023-bsa-talents#86]
Finilize please sign-up process

- [x] check and implement all TODO in sign-up process (password hash, ... etc)
- [x] check sign-up flow

**Comment by Monyster** [comment]
What should be used to encrypt the password?
I think it is bcrypt, am I right?

Where can I store a constant value like SALT_ROUNDS?

I also asked in Slack: https://bsa2023.slack.com/archives/C05NY1E7CBS/p1692820941630339

**Comment by Monyster** [comment]
I complete passwordSalt, passwordHash.

**Comment by anna9314** [comment]
Tested
Got Status Code: 201


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/1062be35-9600-4885-b004-2323e1d78be9)

Got Status Code: 400


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/c7a43e0b-f801-449f-b417-4df8f20e77e2)
