### ISSUE TITLE
Update styles variables

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2023-bsa-talents#89]
- [x] review frontend/src/assets/css/variables.scss
- [x] remove duplication and make universal naming
- [x] add changes with updated variables

Example for naming from our theme: 
https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/blob/development/frontend/src/bundles/common/enums/typography.enum.ts
https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/blob/development/frontend/src/bundles/common/enums/colors.enum.ts

**Comment by Simpsonkk** [comment]
deleted

**Comment by Simpsonkk** [comment]
deleted
