### ISSUE TITLE
Create Drawer navigation UI

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#90]
Create UI for Drawer navigation steps. Each step should lead to a separate screen. The component of each step should have 3 options: disabled, active and completed 

![Image](https://user-images.githubusercontent.com/103518438/262884359-5f541791-ae00-4d9f-819a-e613dc998cf7.png)

**Comment by anna9314** [comment]
Tested


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/63346295/a347589b-b482-45af-9798-751e87585033)
